name: OpenProject
description: OpenProject is an open-source project management software that
  offers efficient classic, agile, or hybrid project management in a secure
  environment. It allows users to take control of their data and protect their
  privacy with data sovereignty. OpenProject provides system and network
  security, free and open-source software (FOSS), and peace of mind hosting in
  the EU. It is suitable for both on-premises installation and cloud hosting.
  With OpenProject, teams can easily connect, structure their work, and achieve
  results. It offers project planning and scheduling, agile project management
  with Scrum and Kanban methodologies, and a team planner to visually assign
  tasks. OpenProject is a leading open-source project management software with a
  large community of users and developers. It offers different hosting options,
  including self-managed, enterprise on-premises, and enterprise cloud.
  OpenProject is trusted by successful companies and has received positive
  feedback from customers.
instructions: The default login credentials are admin:admin
changeLog:
  - date: 2023-03-26
    description: First Release
links:
  - label: Website
    url: https://openproject.org/
  - label: Docs
    url: https://openproject.org/docs/
  - label: Github
    url: https://github.com/opf/openproject
  - label: Docker
    url: https://hub.docker.com/r/openproject/community
contributors:
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: openproject
    appServiceImage:
      type: string
      title: App Service Image
      default: openproject/community:12
tags:
  - Project Management
  - Open Source
benefits:
  - title: Data Sovereignty
    description: OpenProject allows users to take control of their data and protect
      their privacy in a secure environment. Users have full control and 100%
      data ownership, knowing where their data is stored and what happens to it.
  - title: System and Network Security
    description: OpenProject offers the highest level of security and protection of
      data with features such as HTTPS encryption, password security, two-factor
      authentication, and session runtime definition.
  - title: Free and Open-Source Software (FOSS)
    description: OpenProject is free and open-source software, giving users the
      freedom to run, share, study, and modify it without limitations. It is
      licensed under GNU GPL v3.
  - title: Peace of Mind Hosting in the EU
    description: With OpenProject's Enterprise Cloud, data is stored on secure
      servers within the EU. The data center and network architecture are
      designed to meet the needs of highly security-conscious organizations.
features:
  - title: Project Planning and Scheduling
    description: OpenProject allows users to create and visualize project plans with
      shared timelines. It helps analyze required activities and create detailed
      plans to deliver project deliverables on time.
  - title: Agile, Scrum & Kanban
    description: OpenProject supports agile project management and methodologies
      such as Scrum and Kanban. It provides the perfect tool for agile teams to
      build, measure, and learn with each iteration.
  - title: Team Planner
    description: OpenProject's team planner allows users to visually assign tasks to
      team members in a weekly or bi-weekly calendar. It helps plan team
      activities and provides a better perspective on the topics the team is
      working on.
