name: Flame
description: Flame is a self-hosted startpage app for your server. It allows you
  to create, update, and delete applications and bookmarks directly from the app
  using built-in GUI editors. You can pin your favorite items to the homescreen
  for quick and easy access. Flame also includes an integrated search bar with
  local filtering and support for 11 web search providers. It has an
  authentication system to protect your settings, apps, and bookmarks. You can
  customize the Flame interface with dozens of options, including support for
  custom CSS and 15 built-in color themes. It also includes a weather widget
  with current temperature, cloud coverage, and animated weather status. Flame
  can be installed using Docker or without Docker. It supports Docker
  integration and Kubernetes integration. You can also import HTML bookmarks
  into Flame. Flame is written in Node.js + Express on the backend and React
  Redux TypeScript on the frontend.
instructions: null
changeLog:
  - date: 2022-07-12
    description: first release
links:
  - label: Website
    url: https://github.com/pawelmalak/flame
  - label: Documentation
    url: https://github.com/pawelmalak/flame
  - label: Github
    url: https://github.com/pawelmalak/flame
contributors:
  - name: Ponkhy
    url: https://github.com/Ponkhy
  - name: Andrei Canta
    url: https://github.com/deiucanta
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - password
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: flame
    appServiceImage:
      type: string
      title: App Service Image
      default: pawelmalak/flame:multiarch2.3.0
    password:
      type: string
      title: Password
tags:
  - Web Hosting
  - CMS
benefits:
  - title: Easy to setup and use
    description: Flame is very easy to setup and use. It includes built-in editors
      that allow you to setup your own application hub without any file editing.
  - title: Customizable interface
    description: Flame offers dozens of options to customize the interface to your
      needs. You can use custom CSS, choose from 15 built-in color themes, and
      even create your own custom theme.
  - title: Integrated search bar
    description: Flame includes an integrated search bar with local filtering. It
      supports 11 web search providers and allows you to add your own. You can
      search through all your apps and bookmarks or use specific search engines
      with shortcuts.
  - title: Authentication system
    description: Flame has an authentication system to protect your settings, apps,
      and bookmarks. You can set a password to secure your Flame instance.
  - title: Docker and Kubernetes integration
    description: Flame supports Docker integration, allowing you to automatically
      add apps based on their labels. It also supports Kubernetes integration,
      allowing you to add apps using Kubernetes ingresses.
features:
  - title: Create, update, and delete applications and bookmarks
    description: Flame allows you to create, update, and delete applications and
      bookmarks directly from the app using built-in GUI editors. No file
      editing is necessary.
  - title: Pin favorite items to the homescreen
    description: You can pin your favorite items to the homescreen for quick and
      easy access. This allows you to have quick access to your most frequently
      used apps and bookmarks.
  - title: Weather widget
    description: Flame includes a weather widget that displays the current
      temperature, cloud coverage, and animated weather status. You can obtain
      an API key from a Weather API and enter the lat/long for your location to
      enable the weather widget.
