name: Languagetool
description: LanguageTool is a multilingual spelling, style, and grammar checker
  that helps correct or paraphrase texts. It offers browser add-ons for Chrome,
  Edge, Firefox, Safari, and Opera, as well as office plugins for Google Docs,
  Word, OpenOffice, and LibreOffice. It also has desktop apps for macOS and
  Windows. LanguageTool is trusted by organizations such as BMW Group, European
  Union, Spiegel Magazine, Deutsche Presse-Agentur, Blinkist, and Schweizer
  Radio und Fernsehen. It offers a distraction-free writing experience, personal
  dictionary, quality scoring for evaluating style and grammar, and secure
  storage of texts. LanguageTool is available in multiple languages and offers a
  free version with the option to upgrade to premium for advanced punctuation,
  style, and typography suggestions. It also provides a browser add-on that
  works anywhere on the web and offers tips on how to improve text while typing.
  LanguageTool integrates with popular writing apps and programs such as Google
  Docs, Microsoft Word, LibreOffice, and OpenOffice. It helps with spelling
  correction, grammar checking, punctuation fixing, casing confirmation, style
  improvement, and sentence paraphrasing. LanguageTool is suitable for
  professionals, students, and writers, and also offers a proofreading API for
  businesses. It is available in English, German, Spanish, Dutch, French,
  Russian, Italian, Catalan, Portuguese (BR), Portuguese (PT), Ukrainian, and
  Polish.
instructions: null
changeLog:
  - date: 2023-2-24
    description: first release
links:
  - label: Website
    url: https://languagetool.org
  - label: Github
    url: https://github.com/languagetool-org/languagetool
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: languagetool
    appServiceImage:
      type: string
      title: App Service Image
      default: silviof/docker-languagetool:6.0
tags:
  - Productivity
  - Documents
benefits:
  - title: Multilingual Spelling, Style, and Grammar Checker
    description: LanguageTool can check texts in multiple languages for spelling,
      style, and grammar errors, helping users improve the quality of their
      writing.
  - title: Browser Add-ons and Office Plugins
    description: LanguageTool offers browser add-ons for Chrome, Edge, Firefox,
      Safari, and Opera, as well as office plugins for Google Docs, Word,
      OpenOffice, and LibreOffice, making it easy to use the tool in various
      writing environments.
  - title: Desktop Apps for macOS and Windows
    description: LanguageTool provides desktop apps for macOS and Windows, allowing
      users to access the tool directly from their desktop and use it with their
      favorite writing apps.
  - title: Trusted by Organizations
    description: LanguageTool is trusted by organizations such as BMW Group,
      European Union, Spiegel Magazine, Deutsche Presse-Agentur, Blinkist, and
      Schweizer Radio und Fernsehen, ensuring the reliability and effectiveness
      of the tool.
  - title: Distraction-Free Writing Experience
    description: LanguageTool offers a distraction-free writing experience, allowing
      users to focus on their writing without being interrupted by unnecessary
      features or ads.
  - title: Personal Dictionary
    description: LanguageTool allows users to create a personal dictionary, ensuring
      that specific words or terms are not flagged as errors in their writing.
  - title: Quality Scoring for Evaluating Style and Grammar
    description: LanguageTool provides quality scoring to evaluate the style and
      grammar of texts, helping users identify areas for improvement and enhance
      the overall quality of their writing.
  - title: Secure Storage of Texts
    description: LanguageTool securely stores texts, ensuring that users' writing is
      protected and can be accessed whenever needed.
  - title: Free Version with Upgrade Option
    description: LanguageTool offers a free version with basic spelling, style, and
      grammar checking. Users also have the option to upgrade to the premium
      version for advanced punctuation, style, and typography suggestions.
  - title: Browser Add-on for Web Texts
    description: LanguageTool provides a browser add-on that works anywhere on the
      web, offering tips on how to improve text while typing an email, blog
      post, or social media update.
  - title: Integration with Popular Writing Apps and Programs
    description: LanguageTool integrates with popular writing apps and programs such
      as Google Docs, Microsoft Word, LibreOffice, and OpenOffice, making it
      easy to use the tool with the user's preferred writing environment.
  - title: Spelling Correction
    description: LanguageTool helps users correct spelling errors, ensuring that
      every word is spelled correctly in their writing.
  - title: Grammar Checking
    description: LanguageTool detects grammar errors in texts, helping users improve
      the grammatical accuracy of their writing.
  - title: Punctuation Fixing
    description: LanguageTool helps users fix punctuation errors, ensuring that
      commas, dashes, hyphens, and other punctuation marks are used correctly in
      their writing.
  - title: Casing Confirmation
    description: LanguageTool confirms the correct casing of words, names, months,
      places, and national identities, helping users maintain consistent
      capitalization in their writing.
  - title: Style Improvement
    description: LanguageTool helps users improve the style of their writing by
      detecting overused phrases, foreign terms, redundant words, and improper
      word choices.
  - title: Sentence Paraphrasing
    description: LanguageTool uses artificial intelligence to rephrase sentences,
      making it easier for users to find the right words and improve the
      fluency, simplicity, formality, or conciseness of their writing.
  - title: Proofreading API for Businesses
    description: LanguageTool offers a proofreading API for businesses, allowing
      them to integrate the tool into their own applications or services and
      provide advanced spelling, style, and grammar checking to their users.
features:
  - title: Multilingual Spelling, Style, and Grammar Checking
    description: LanguageTool can check texts in multiple languages for spelling,
      style, and grammar errors, helping users improve the quality of their
      writing.
  - title: Browser Add-ons and Office Plugins
    description: LanguageTool offers browser add-ons for Chrome, Edge, Firefox,
      Safari, and Opera, as well as office plugins for Google Docs, Word,
      OpenOffice, and LibreOffice, making it easy to use the tool in various
      writing environments.
  - title: Desktop Apps for macOS and Windows
    description: LanguageTool provides desktop apps for macOS and Windows, allowing
      users to access the tool directly from their desktop and use it with their
      favorite writing apps.
  - title: Trusted by Organizations
    description: LanguageTool is trusted by organizations such as BMW Group,
      European Union, Spiegel Magazine, Deutsche Presse-Agentur, Blinkist, and
      Schweizer Radio und Fernsehen, ensuring the reliability and effectiveness
      of the tool.
  - title: Distraction-Free Writing Experience
    description: LanguageTool offers a distraction-free writing experience, allowing
      users to focus on their writing without being interrupted by unnecessary
      features or ads.
  - title: Personal Dictionary
    description: LanguageTool allows users to create a personal dictionary, ensuring
      that specific words or terms are not flagged as errors in their writing.
  - title: Quality Scoring for Evaluating Style and Grammar
    description: LanguageTool provides quality scoring to evaluate the style and
      grammar of texts, helping users identify areas for improvement and enhance
      the overall quality of their writing.
  - title: Secure Storage of Texts
    description: LanguageTool securely stores texts, ensuring that users' writing is
      protected and can be accessed whenever needed.
  - title: Free Version with Upgrade Option
    description: LanguageTool offers a free version with basic spelling, style, and
      grammar checking. Users also have the option to upgrade to the premium
      version for advanced punctuation, style, and typography suggestions.
  - title: Browser Add-on for Web Texts
    description: LanguageTool provides a browser add-on that works anywhere on the
      web, offering tips on how to improve text while typing an email, blog
      post, or social media update.
  - title: Integration with Popular Writing Apps and Programs
    description: LanguageTool integrates with popular writing apps and programs such
      as Google Docs, Microsoft Word, LibreOffice, and OpenOffice, making it
      easy to use the tool with the user's preferred writing environment.
  - title: Spelling Correction
    description: LanguageTool helps users correct spelling errors, ensuring that
      every word is spelled correctly in their writing.
  - title: Grammar Checking
    description: LanguageTool detects grammar errors in texts, helping users improve
      the grammatical accuracy of their writing.
  - title: Punctuation Fixing
    description: LanguageTool helps users fix punctuation errors, ensuring that
      commas, dashes, hyphens, and other punctuation marks are used correctly in
      their writing.
  - title: Casing Confirmation
    description: LanguageTool confirms the correct casing of words, names, months,
      places, and national identities, helping users maintain consistent
      capitalization in their writing.
  - title: Style Improvement
    description: LanguageTool helps users improve the style of their writing by
      detecting overused phrases, foreign terms, redundant words, and improper
      word choices.
  - title: Sentence Paraphrasing
    description: LanguageTool uses artificial intelligence to rephrase sentences,
      making it easier for users to find the right words and improve the
      fluency, simplicity, formality, or conciseness of their writing.
  - title: Proofreading API for Businesses
    description: LanguageTool offers a proofreading API for businesses, allowing
      them to integrate the tool into their own applications or services and
      provide advanced spelling, style, and grammar checking to their users.
