name: Ghost
description: Ghost is a powerful app for new-media creators to publish, share,
  and grow a business around their content. It comes with modern tools to build
  a website, publish content, send newsletters & offer paid subscriptions to
  members.
instructions: null
changeLog:
  - date: 2022-07-12
    description: first release
  - date: 2023-02-24
    description: Update to v5.35.1
  - date: 2023-06-30
    description: Update to v5.53.3
links:
  - label: Website
    url: https://ghost.org/
  - label: Documentation
    url: https://ghost.org/resources/
  - label: Github
    url: https://github.com/docker-library/ghost
contributors:
  - name: Andrei Canta
    url: https://github.com/deiucanta
  - name: Supernova3339
    url: https://github.com/supernova3339
  - name: siriokun
    url: https://github.com/siriokun
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: ghost
    appServiceImage:
      type: string
      title: App Service Image
      default: ghost:5.53.3-alpine
    databaseServiceName:
      type: string
      title: Database Service Name
      default: ghost-db
tags:
  - Business Apps
  - CMS
benefits:
  - title: Advanced Creator Tools
    description: Launch your website with a selection of beautiful free themes and
      customize the design to match your brand. Publish content with an editor
      designed for professionals and enhance your stories with rich media and
      dynamic cards.
  - title: Grow Your Audience
    description: Turn anonymous views into logged-in members with native signup
      forms. Offer free or paid subscriptions to support your work and engage
      with your audience through newsletters.
  - title: Run Your Business
    description: Manage memberships, track engagement analytics, and run offers and
      promotions to grow your business.
  - title: Integrations
    description: Ghost integrates with various tools and platforms, including
      GeckoBoard, MailChimp, Pinterest, Buffer, Twitter, Stripe, Instagram,
      YouTube, Google Analytics, and more.
  - title: Creator Stats
    description: Ghost publishers earn over $25,000,000 in revenue each year with 0%
      payment fees. Prominent creators like Ali Abdaal, David Sirota, and Buffer
      use Ghost for their content.
  - title: Built to Last
    description: Ghost is open source, independent, and funded by its users. It
      provides a reliable platform for creators to launch their websites and
      build their businesses.
features:
  - title: Advanced Creator Tools
    description: Launch your website with beautiful free themes or create a custom
      design. Publish content with a professional editor and enhance it with
      rich media and dynamic cards.
  - title: Publish by Web & Email Newsletter
    description: Deliver posts by email newsletter to your audience and segment them
      based on preference.
  - title: Grow Your Audience
    description: Turn anonymous views into logged-in members with native signup
      forms. Offer free or paid subscriptions to support your work.
  - title: Run Your Business
    description: Manage memberships, track engagement analytics, and run offers and
      promotions to grow your business.
  - title: Integrations
    description: Connect Ghost with various tools and platforms to enhance your
      workflow and reach.
  - title: Creator Stats
    description: Ghost publishers earn over $25,000,000 in revenue each year with 0%
      payment fees. Prominent creators like Ali Abdaal, David Sirota, and Buffer
      use Ghost for their content.
  - title: Built to Last
    description: Ghost is open source, independent, and funded by its users. It
      provides a reliable platform for creators to launch their websites and
      build their businesses.
