name: Filerun
description: FileRun is a private file sharing and collaboration platform that
  allows you to access and manage your files from anywhere. It runs fast on any
  hardware and supports various file types. With FileRun, you can easily
  organize and share your files, collaborate with others, and access your files
  through FTP, SMB, or WebDAV. It also offers features like desktop sync,
  virtual drive, metadata support, guest users, file requests, and various
  plugins for editing and previewing files. FileRun is secure, customizable, and
  comes with extensive features and options.
instructions: null
changeLog:
  - date: 2023-3-14
    description: first release
links:
  - label: Website
    url: https://filerun.com/
  - label: Documentation
    url: https://docs.filerun.com
contributors:
  - name: Supernova3339
    url: https://github.com/supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: filerun
    appServiceImage:
      type: string
      title: App Service Image
      default: filerun/filerun # no versioned images
    databaseServiceName:
      type: string
      title: Database Service Name
      default: filerun-db
tags:
  - File Management
  - Communication
benefits:
  - title: Private and under your control
    description: Unlike other file sharing platforms, FileRun gives you full control
      over your files. It runs on your own server, ensuring the privacy and
      security of your data.
  - title: Fast and versatile
    description: FileRun runs fast on any hardware, including Linux, Windows, VPS,
      shared hosting, and NAS. It supports various file types and allows you to
      access your files through FTP, SMB, or WebDAV.
  - title: Easy file management
    description: With FileRun, you can easily manage your files without the need for
      import or scanning. Simply point FileRun to the location of your files on
      your server, and you'll get instant web access to them.
  - title: Collaboration made easy
    description: FileRun allows you to collaborate with others without creating
      accounts for them. You can share files with guest users and collect files
      from anyone using file requests.
  - title: Extensive features and plugins
    description: FileRun offers a wide range of features, including desktop sync,
      virtual drive, metadata support, timeline browsing for photos and videos,
      file versioning, and more. It also supports various plugins for editing
      and previewing files.
features:
  - title: Private and under your control
    description: FileRun runs on your own server, ensuring the privacy and security
      of your files. You have full control over your data.
  - title: Fast and versatile
    description: FileRun runs fast on any hardware, including Linux, Windows, VPS,
      shared hosting, and NAS. It supports various file types and access
      methods.
  - title: Easy file management
    description: No import or scanning required. Simply point FileRun to the
      location of your files on your server, and you'll get instant web access
      to them. You can also access your files through FTP, SMB, or WebDAV.
  - title: Collaboration made easy
    description: Collaborate with others without creating accounts for them. Share
      files with guest users and collect files from anyone using file requests.
  - title: Desktop sync
    description: Sync files using desktop apps and access your files from anywhere
      using compatible mobile apps.
  - title: Virtual drive
    description: Access files directly from your computer without impacting disk
      space. Spend less time waiting for files to sync.
  - title: Metadata support
    description: Automatically extract and index information from files, such as
      Exif, XMP, and IPTC. Search photos by keywords, dates, author, and more.
      Add custom metadata fields.
  - title: Timeline browsing for photos and videos
    description: Sort photos and videos chronologically. Group photos together in
      virtual albums and share them online.
  - title: Various plugins
    description: FileRun offers various plugins for creating, editing, and
      previewing files, including Google Docs Editor, Zoho Editor, ONLYOFFICE,
      Office Web View, LibreOffice Integration, Autodesk Preview, EPUB reader,
      and more.
  - title: Secure
    description: FileRun provides protection against XSS, CSRF, SQL injections,
      session hijacking, and brute force login attempts. It supports HTTPS/SSL
      and offers automatic file versioning and trash folder for deleted files.
  - title: Customizable
    description: Customize FileRun with your own branding, including color presets,
      background images, logos, and more. Choose from various themes and set
      file space quotas.
  - title: Loaded with features
    description: FileRun offers a range of features, including full text file
      indexing and searching, 2-factor authentication, user roles and groups,
      user activity feed, per-file activity log, file locking, per-folder
      notifications, and more.
