name: Lavalink
description: Lavalink is a standalone audio sending node based on Lavaplayer and
  Koe. It allows for sending audio without it ever reaching any of your shards.
  It is being used in production by FredBoat, Dyno, LewdBot, and more.
instructions: null
changeLog:
  - date: 2019-07-24
    description: first release
links:
  - label: Documentation
    url: https://github.com/freyacodes/Lavalink/blob/master/README.md
  - label: Github
    url: https://github.com/freyacodes/Lavalink
contributors:
  - name: kaname-png
    url: https://github.com/kaname-png
schema:
  type: object
  required:
    - projectName
    - password
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    password:
      type: string
      title: Auth server password
    appServiceName:
      type: string
      title: App Service Name
      default: lavalink-server
    appServiceImage:
      type: string
      title: App Service Image
      default: fredboat/lavalink:v3.7
tags:
  - Audio
  - Developer Tools
benefits:
  - title: Powered by Lavaplayer
    description: Lavalink is powered by Lavaplayer, a powerful audio player library
      for Java. This ensures high-quality audio playback and support for various
      audio sources.
  - title: Minimal CPU/memory footprint
    description: Lavalink is designed to have a minimal impact on CPU and memory
      usage, allowing it to run efficiently even on resource-constrained
      systems.
  - title: Twitch/YouTube stream support
    description: Lavalink supports streaming audio from Twitch and YouTube, allowing
      you to play live streams in your application.
  - title: Event system
    description: Lavalink provides an event system that allows you to listen for
      various events, such as track start, track end, and player update. This
      makes it easy to build interactive audio applications.
  - title: Seeking
    description: Lavalink supports seeking within audio tracks, allowing users to
      skip to a specific position in a track.
  - title: Volume control
    description: Lavalink provides volume control functionality, allowing users to
      adjust the volume of the audio playback.
  - title: REST API
    description: Lavalink offers a REST API for resolving Lavaplayer tracks,
      controlling players, and more. This API can be used to integrate Lavalink
      with other services or build custom applications.
  - title: Statistics
    description: Lavalink provides statistics that are useful for load balancing.
      These statistics can help you monitor the performance of your audio nodes
      and make informed decisions about resource allocation.
  - title: Basic authentication
    description: Lavalink supports basic authentication, allowing you to secure your
      audio nodes and restrict access to authorized users.
  - title: Prometheus metrics
    description: Lavalink includes Prometheus metrics that provide detailed
      information about the performance and usage of your audio nodes. These
      metrics can be used for monitoring and troubleshooting purposes.
  - title: Docker support
    description: Lavalink provides Docker images, making it easy to deploy and
      manage your audio nodes in containerized environments.
  - title: Plugin support
    description: Lavalink supports plugins, allowing you to extend its functionality
      and customize its behavior to suit your specific needs.
features:
  - title: Powered by Lavaplayer
    description: Lavalink is built on top of Lavaplayer, a powerful audio player
      library for Java. This ensures high-quality audio playback and support for
      various audio sources, including YouTube, SoundCloud, Bandcamp, and more.
  - title: Minimal CPU/memory footprint
    description: Lavalink is designed to have a minimal impact on CPU and memory
      usage, allowing it to run efficiently even on resource-constrained
      systems. This makes it suitable for running on low-end hardware or in
      cloud environments with limited resources.
  - title: Twitch/YouTube stream support
    description: Lavalink supports streaming audio from Twitch and YouTube, allowing
      you to play live streams in your application. This is useful for
      applications that require real-time audio playback, such as music bots or
      live streaming platforms.
  - title: Event system
    description: Lavalink provides an event system that allows you to listen for
      various events, such as track start, track end, and player update. This
      makes it easy to build interactive audio applications that respond to user
      actions or track changes.
  - title: Seeking
    description: Lavalink supports seeking within audio tracks, allowing users to
      skip to a specific position in a track. This is useful for applications
      that require precise control over audio playback, such as podcast players
      or audio editing tools.
  - title: Volume control
    description: Lavalink provides volume control functionality, allowing users to
      adjust the volume of the audio playback. This is useful for applications
      that require dynamic volume adjustments, such as music players or voice
      chat systems.
  - title: REST API
    description: Lavalink offers a REST API for resolving Lavaplayer tracks,
      controlling players, and more. This API can be used to integrate Lavalink
      with other services or build custom applications that interact with the
      audio nodes.
  - title: Statistics
    description: Lavalink provides statistics that are useful for load balancing.
      These statistics include information about the number of active players,
      CPU and memory usage, and network traffic. This allows you to monitor the
      performance of your audio nodes and make informed decisions about resource
      allocation.
  - title: Basic authentication
    description: Lavalink supports basic authentication, allowing you to secure your
      audio nodes and restrict access to authorized users. This is important for
      applications that handle sensitive audio content or require user
      authentication for accessing the audio nodes.
  - title: Prometheus metrics
    description: Lavalink includes Prometheus metrics that provide detailed
      information about the performance and usage of your audio nodes. These
      metrics can be used for monitoring and troubleshooting purposes, allowing
      you to identify and resolve performance issues quickly.
  - title: Docker support
    description: Lavalink provides Docker images, making it easy to deploy and
      manage your audio nodes in containerized environments. This simplifies the
      deployment process and allows you to take advantage of containerization
      benefits, such as scalability, portability, and isolation.
  - title: Plugin support
    description: Lavalink supports plugins, allowing you to extend its functionality
      and customize its behavior to suit your specific needs. You can develop
      and install plugins to add new features, integrate with external services,
      or enhance the existing functionality of Lavalink.
