name: Drone
description: Drone.io is a self-service Continuous Integration platform for busy
  development teams. It allows teams to automate software build and testing
  processes.
instructions: null
changeLog:
  - date: 2022-08-04
    description: first release
links:
  - label: Website
    url: https://drone.io/
  - label: Documentation
    url: https://github.com/harness/drone#setup-documentation
  - label: Github
    url: https://github.com/harness/drone
contributors:
  - name: Ivan Ryan
    url: https://github.com/ivanonpc-22
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - runnerServiceName
    - runnerServiceImage
    - clientID
    - clientSecret
    - rpcHost
    - rpcProtocol
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: drone
    appServiceImage:
      type: string
      title: App Service Image
      default: drone/drone:2.16.0
    runnerServiceName:
      type: string
      title: Runner Service Name
      default: drone-runner
    runnerServiceImage:
      type: string
      title: Runner Service Image
      default: drone/drone-runner-docker:1.8.3
    clientID:
      type: string
      title: GitHub OAuth Client ID
    clientSecret:
      type: string
      title: GitHub OAuth Client Secret
      default: secret
    rpcHost:
      type: string
      title: RPC Host
    rpcProtocol:
      type: string
      title: RPC Protocol
      default: https
      oneOf:
        - enum:
            - https
          title: https
        - enum:
            - http
          title: http
    installRunner:
      type: boolean
      title: Install Runner Service
      default: false
    runnerCapacity:
      type: number
      title: Capacity for runner if enabled
      default: 2
tags:
  - Code Hosting
  - Developer Tools
benefits:
  - title: Configuration as a code
    description: Pipelines are configured with a simple, easy-to-read file that you
      commit to your git repository.
  - title: Any Source Code Manager
    description: Drone integrates seamlessly with multiple source code management
      systems, including GitHub, GitHub Enterprise, Bitbucket, and GitLab.
  - title: Any Platform
    description: Drone natively supports multiple operating systems and
      architectures, including Linux x64, ARM, ARM64, and Windows x64.
  - title: Any Language
    description: Drone works with any language, database, or service that runs
      inside a Docker container.
  - title: Create & Share Plugins
    description: Drone uses containers to drop pre-configured steps into your
      pipeline. Choose from hundreds of existing plugins or create your own.
  - title: Customization When You Need It
    description: Drone makes advanced customization easy. Implement custom access
      controls, approval workflows, secret management, YAML syntax extensions,
      and more.
  - title: Simple Configuration
    description: Don’t waste time configuring your build servers. Choose from
      thousands of Docker images and Drone will auto-provision your environment.
  - title: Isolated Builds
    description: Don’t worry about conflicting builds on shared servers. Every build
      runs in an isolated Docker container, giving you full control.
  - title: Effortless Scaling
    description: Drone installs from a single binary and scales automatically.
features:
  - title: Configuration as a code
    description: Pipelines are configured with a simple, easy-to-read file that you
      commit to your git repository.
  - title: Any Source Code Manager
    description: Drone integrates seamlessly with multiple source code management
      systems, including GitHub, GitHub Enterprise, Bitbucket, and GitLab.
  - title: Any Platform
    description: Drone natively supports multiple operating systems and
      architectures, including Linux x64, ARM, ARM64, and Windows x64.
  - title: Any Language
    description: Drone works with any language, database, or service that runs
      inside a Docker container.
  - title: Create & Share Plugins
    description: Drone uses containers to drop pre-configured steps into your
      pipeline. Choose from hundreds of existing plugins or create your own.
  - title: Customization When You Need It
    description: Drone makes advanced customization easy. Implement custom access
      controls, approval workflows, secret management, YAML syntax extensions,
      and more.
  - title: Simple Configuration
    description: Don’t waste time configuring your build servers. Choose from
      thousands of Docker images and Drone will auto-provision your environment.
  - title: Isolated Builds
    description: Don’t worry about conflicting builds on shared servers. Every build
      runs in an isolated Docker container, giving you full control.
  - title: Effortless Scaling
    description: Drone installs from a single binary and scales automatically.
