name: Jellyseerr
description: Jellyseerr is a free and open source software application for
  managing requests for your media library. It is a fork of Overseerr built to
  bring support for Jellyfin & Emby media servers!
instructions: none
changeLog:
  - date: 2022-12-20
    description: first release
links:
  - label: Documentation
    url: https://github.com/Fallenbagel/jellyseerr/tree/develop/docs
  - label: Github
    url: https://github.com/Fallenbagel/jellyseerr
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: jellyseerr
    appServiceImage:
      type: string
      title: App Service Image
      default: fallenbagel/jellyseerr:1.3.0
tags:
  - Media
  - Developer Tools
benefits:
  - title: Full Jellyfin/Emby/Plex integration
    description: Authenticate and manage user access with Jellyfin/Emby/Plex!
      Supports Movies, Shows, Mixed Libraries!
  - title: Easy integration with existing services
    description: Currently supports Sonarr and Radarr. More to come!
  - title: Customizable request system
    description: Allows users to request individual seasons or movies in a friendly,
      easy-to-use interface.
  - title: Simple request management UI
    description: Easily approve recent requests without digging through the app.
  - title: Granular permission system
    description: Manage user permissions with fine-grained control.
  - title: Support for various notification agents
    description: Receive notifications through different channels.
  - title: Mobile-friendly design
    description: Approve requests on the go with a mobile-friendly interface.
features:
  - title: Full Jellyfin/Emby/Plex integration
    description: Authenticate and manage user access with Jellyfin/Emby/Plex!
      Supports Movies, Shows, Mixed Libraries!
  - title: Ability to change email addresses for SMTP purposes
    description: Customize email addresses for SMTP configuration.
  - title: Ability to import all Jellyfin/Emby users
    description: Import all users from Jellyfin/Emby for easy access management.
  - title: Easy integration with existing services
    description: Currently supports Sonarr and Radarr. More to come!
  - title: Jellyfin/Emby/Plex library scan
    description: Keep track of the titles that are already available in your library.
  - title: Customizable request system
    description: Allows users to request individual seasons or movies in a friendly,
      easy-to-use interface.
  - title: Simple request management UI
    description: Easily approve recent requests without digging through the app.
  - title: Granular permission system
    description: Manage user permissions with fine-grained control.
  - title: Support for various notification agents
    description: Receive notifications through different channels.
  - title: Mobile-friendly design
    description: Approve requests on the go with a mobile-friendly interface.
  - title: Multiple Server Instances (Upcoming)
    description: Run multiple instances of Jellyseerr for different media servers.
  - title: Music Support (Upcoming)
    description: Support for managing music requests in addition to movies and TV shows.
