name: Homarr
description: Homarr is a simple yet powerful dashboard for your server. It
  allows you to easily manage and access all of your apps and services in one
  convenient location. With seamless integrations, customizable features, and
  support for multiple languages, Homarr provides a user-friendly experience for
  server management.
instructions: null
changeLog:
  - date: 2022-12-20
    description: First Release
links:
  - label: Website
    url: https://homarr.dev/
  - label: Documentation
    url: https://homarr.dev/docs
  - label: Github
    url: https://github.com/ajnart/homarr
contributors:
  - name: DrMxrcy
    url: https://github.com/DrMxrcy
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: homarr
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/ajnart/homarr:0.11.2
    serviceTimezone:
      type: string
      title: Timezone
      default: America/New_York
tags:
  - "Dashboard "
  - Documentation
benefits:
  - title: Simplify Server Management
    description: Homarr streamlines the management of your server by providing a
      sleek and modern dashboard that puts all of your apps and services at your
      fingertips. With Homarr, you can easily access and control everything in
      one place.
  - title: Seamless Integrations
    description: Homarr seamlessly integrates with popular applications, enhancing
      your experience and providing valuable information. It supports over 15
      integrations, including Radarr, Sonarr, PiHole, Dash, and popular Torrent
      & Usenet clients.
  - title: Customizable and Multi-lingual
    description: Homarr is highly customizable, accessible, and supports 23
      languages. You can personalize your dashboard by adding your self-hosted
      applications or favorite websites, and organize them as you like.
  - title: Open Source
    description: Homarr is an open-source project, allowing you to view, modify, and
      distribute the entire source code. It also supports commercial usage, but
      donations are appreciated to cover infrastructure costs.
features:
  - title: Organize Your Applications
    description: Add your self-hosted applications or favorite websites to your
      dashboard and freely organize them using the drag-and-drop feature.
  - title: Widgets
    description: Use integrations to display data and control apps, including
      Radarr, Sonarr, PiHole, Dash, popular Torrent & Usenet clients, and many
      more.
  - title: Quick Search
    description: Search through your apps and supported integrations instantly to
      find what you need.
  - title: Create Your Own Dashboard
    description: Easily create your own dashboard using Homarr's visual editor,
      without the need for YAML or JSON.
