name: Shiori
description: Shiori is a simple bookmarks manager written in the Go language. It
  is intended as a simple clone of Pocket and can be used as a command line
  application or as a web application. It supports basic bookmarks management,
  import and export of bookmarks, a simple and clean command line interface, a
  simple and pretty web interface, and is portable thanks to its single binary
  format. It also supports multiple databases and can create offline archives of
  webpages. There is also a web extension available for managing bookmarks using
  Shiori.
instructions: The default account is "shiori" with password "gopher". It is
  removed once another "owner" account is created.
changeLog:
  - date: 2023-03-17
    description: Template created (v1.5.4)
links:
  - label: Github
    url: https://github.com/go-shiori/shiori
  - label: Web Extension
    url: https://github.com/go-shiori/shiori-web-ext
contributors:
  - name: Ponkhy
    url: https://github.com/Ponkhy
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: shiori
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/go-shiori/shiori:v1.5.4
    databaseServiceName:
      type: string
      title: Database Service Name
      default: shiori-db
tags:
  - Code Hosting
  - Bookmarks
benefits:
  - title: Simple and Easy to Use
    description: Shiori provides a simple and clean interface for managing
      bookmarks, making it easy to add, edit, delete, and search for bookmarks.
  - title: Portable and Easy to Install
    description: Shiori is distributed as a single binary, which means it can be
      easily installed and used on any system without the need for complex setup
      or dependencies.
  - title: Supports Multiple Databases
    description: Shiori supports sqlite3, PostgreSQL, and MySQL as its database,
      giving you the flexibility to choose the database that works best for you.
  - title: Web Extension Support
    description: Shiori has a web extension available for Firefox and Chrome,
      allowing you to save and remove bookmarks in Shiori without switching from
      your current page.
features:
  - title: Basic Bookmarks Management
    description: Shiori allows you to add, edit, delete, and search for bookmarks,
      providing a simple and efficient way to manage your bookmarks.
  - title: Import and Export Bookmarks
    description: Shiori supports importing and exporting bookmarks from and to
      Netscape Bookmark file, as well as importing bookmarks from Pocket.
  - title: Command Line and Web Interface
    description: Shiori can be used as a command line application or as a web
      application, providing flexibility in how you interact with your
      bookmarks.
  - title: Offline Archive of Webpages
    description: Shiori can parse the readable content of webpages and create an
      offline archive, allowing you to access the content even when you are
      offline.
