name: Ackee
description: Ackee is a self-hosted, Node.js based analytics tool that cares
  about privacy. It runs on your own server, analyzes the traffic of your
  websites, and provides useful statistics in a minimal interface.
instructions: null
changeLog:
  - date: 2022-06-04
    description: first release
links:
  - label: Website
    url: https://ackee.electerious.com/
  - label: Documentation
    url: https://docs.ackee.electerious.com/
  - label: Github
    url: https://github.com/electerious/Ackee
contributors:
  - name: Ponkhy
    url: https://github.com/Ponkhy
schema:
  type: object
  required:
    - projectName
    - ackeeUsername
    - ackeePassword
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    ackeeUsername:
      type: string
      title: Ackee Username
    ackeePassword:
      type: string
      title: Ackee Password
    appServiceName:
      type: string
      title: App Service Name
      default: ackee
    appServiceImage:
      type: string
      title: App Service Image
      default: electerious/ackee:3.4.2
    databaseServiceName:
      type: string
      title: Database Service Name
      default: ackee-db
tags:
  - Analytics
  - Privacy
benefits:
  - title: Privacy-focused analytics
    description: Ackee keeps tracked data anonymized to avoid identifying users,
      while still providing helpful insights.
  - title: Self-hosted and open-source
    description: Ackee runs on your own server and is 100% open-source, giving you
      complete control over your data.
  - title: Easy to integrate
    description: Add a tracking script to your sites, similar to Google Analytics,
      and start analyzing your data.
features:
  - title: Next level analytics
    description: Ackee combines privacy-focused analytics and first-class insights
      in a minimal interface.
  - title: Data made beautiful
    description: The minimal UI of Ackee allows you to analyze your data without
      losing focus.
  - title: Safe and anonymous
    description: Ackee uses a multi-step anonymization process to ensure the privacy
      of your users.
  - title: Unlimited domains
    description: Analyze as many domains and apps as you want with Ackee.
