name: Isso
description: Isso is a lightweight commenting server similar to Disqus. It
  allows anonymous comments, maintains identity, and is simple to administrate.
  It uses JavaScript and cross-origin resource sharing for easy integration into
  (static) websites.
instructions: Go to /admin for administration interface
changeLog:
  - date: 2023-2-9
    description: first release
links:
  - label: Documentation
    url: https://isso-comments.de/docs/
  - label: Github
    url: https://github.com/posativ/isso
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - adminPassword
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: isso
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/isso-comments/isso:0.13.0
    adminPassword:
      type: string
      title: Admin Password
tags:
  - Developer Tools
  - CMS
benefits:
  - title: Anonymous Comments
    description: Isso allows users to leave anonymous comments on websites.
  - title: Maintains Identity
    description: Isso maintains the identity of commenters, allowing them to edit or
      delete their own comments.
  - title: Simple Administration
    description: Isso is easy to administrate, making it simple to manage comments
      on websites.
  - title: Easy Integration
    description: Isso uses JavaScript and cross-origin resource sharing for easy
      integration into (static) websites.
features:
  - title: Comments in Markdown
    description: Isso supports comments written in Markdown.
  - title: Comment Moderation
    description: Comments in the moderation queue are not publicly visible until activated.
  - title: SQLite Backend
    description: Isso uses SQLite as its backend for storing comments.
  - title: Disqus & WordPress Import
    description: Isso allows for easy migration of comments from Disqus or WordPress.
  - title: Configurable JS Client
    description: Isso provides a configurable JavaScript client for embedding
      comments on websites.
