name: Bazarr
description: Bazarr is a companion application to Sonarr and Radarr that manages
  and downloads subtitles based on your requirements.
instructions: null
changeLog:
  - date: 2023-3-17
    description: first release
links:
  - label: Website
    url: https://bazarr.media/
  - label: Documentation
    url: https://wiki.bazarr.media/
  - label: Github
    url: https://github.com/morpheus65535/bazarr
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: bazarr
    appServiceImage:
      type: string
      title: App Service Image
      default: lscr.io/linuxserver/bazarr:1.2.0
tags:
  - Media
  - Developer Tools
benefits:
  - title: Automatic search
    description: Search automatically for missing subtitles and download them as
      soon as they become available in your desired language.
  - title: Manual search
    description: Find all the matching subtitles, choose the one you want and
      download it to your media directory with the proper name to be used by
      your media player.
  - title: Subtitles upgrade
    description: Search for matching subtitles on a regular basis and upgrade the
      one you previously downloaded if a better one is found.
features:
  - title: Download
    description: Linux, Windows and macOS
  - title: Running from python sources
    description: Automatic Updates
  - title: Fully isolated from the host
    description: Automatic Updates
