name: Umami
description: Umami is an open source, privacy-focused alternative to Google
  Analytics. It allows you to gather the data you need while respecting the
  privacy of your users. Umami does not collect any personal information, does
  not use cookies, does not track users across websites, and is GDPR compliant.
  It helps you stay compliant with data privacy laws by anonymizing all
  collected data. Umami is easy to use and understand, with simple analytics
  that fit on a single page. It is an open source project that is transparent,
  battle-tested, and community supported.
instructions: You can login with username "admin" and password "umami".
changeLog:
  - date: 2022-09-27
    description: first release
links:
  - label: Website
    url: https://umami.is/
  - label: Github
    url: https://github.com/umami-software/umami
  - label: Documentation
    url: https://umami.is/docs
contributors:
  - name: Andrei Canta
    url: https://github.com/deiucanta
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: umami
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/umami-software/umami:postgresql-latest
    databaseServiceName:
      type: string
      title: Database Service Name
      default: umami-db
tags:
  - Analytics
  - Privacy
benefits:
  - title: Privacy-focused
    description: Umami does not collect any personal information, does not use
      cookies, does not track users across websites, and is GDPR compliant.
  - title: Own your data
    description: All data collected by Umami is anonymized, making it impossible to
      identify any individual user. Your data is securely in your hands.
  - title: Simple analytics
    description: Umami collects only the metrics you care about and presents them on
      a single page, making it easy to use and understand.
  - title: Open source
    description: Umami is an open source project that is fully transparent,
      battle-tested, and community supported.
features:
  - title: Privacy-focused alternative to Google Analytics
    description: Umami is designed to respect the privacy of your users by not
      collecting any personal information, not using cookies, not tracking users
      across websites, and being GDPR compliant.
  - title: Anonymized data collection
    description: Umami anonymizes all collected data, making it impossible to
      identify any individual user.
  - title: Easy to use and understand
    description: Umami collects only the metrics you care about and presents them on
      a single page, making it simple to use and understand.
  - title: Open source development
    description: Umami is an open source project that is fully transparent,
      battle-tested, and community supported.
