name: Supertokens Core
description: SuperTokens is an authentication solution that allows developers to
  build secure and customizable user authentication systems for their
  applications. It offers features such as user roles, two-factor
  authentication, single sign-on (SSO), session management, user management, and
  account linking. SuperTokens can be easily integrated into any application
  using its frontend SDKs and helper functions. It is trusted by startups and
  enterprises alike and can be set up in just 5 minutes. SuperTokens is
  reasonably priced and offers hosted solutions on your own domain, eliminating
  the need for redirects. It also supports multi-tenant SSO and can be
  configured to work with Okta, Microsoft AD, and SAML per customer. SuperTokens
  has received positive feedback from users and has been praised for its
  simplicity, customizability, and responsive support. It is used by top
  companies and has been featured in case studies showcasing its effectiveness
  in preventing fraud and improving authentication for businesses. SuperTokens
  is an open-source project with a large community of contributors and offers
  extensive documentation and resources for developers. It is backed by
  Y-Combinator and has raised $300 million in funding. SuperTokens works with
  over 25 frameworks and is compatible with various authentication methods such
  as email/password login, social login (OAuth), and passwordless login. It
  provides guides, implementation recipes, and API references to help developers
  get started. SuperTokens is committed to security and is SOC2 compliant,
  ensuring the protection of over 5 million identities. The company has a strong
  focus on customer support, with 99.9% uptime and a quick response time to user
  requests. SuperTokens offers a free trial and has a pricing model that suits
  different business needs. The company is actively developing new features and
  has a roadmap for future enhancements. SuperTokens is actively hiring and
  invites talented individuals to join their team.
instructions: Check environment tab for your API key
changeLog:
  - date: 2023-2-22
    description: first release
links:
  - label: Website
    url: https://supertokens.com/
  - label: Documentation
    url: https://supertokens.com/docs
  - label: Github
    url: https://github.com/supertokens
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: supertokens-core
    appServiceImage:
      type: string
      title: App Service Image
      default: supertokens/supertokens-postgresql:4.3
    databaseServiceName:
      type: string
      title: Database Service Name
      default: supertokens-core-db
tags:
  - Developer Tools
  - Security
benefits:
  - title: Build fast
    description: SuperTokens allows developers to quickly build secure and
      customizable user authentication systems for their applications.
  - title: Maintain control
    description: With SuperTokens, developers have full control over the
      authentication process and can customize it to meet their specific
      requirements.
  - title: Reasonably priced
    description: SuperTokens offers a pricing model that is affordable for startups
      and enterprises, making it a cost-effective solution for user
      authentication.
features:
  - title: User roles
    description: SuperTokens provides user role management, allowing developers to
      assign different roles and permissions to users.
  - title: Two-factor authentication (2FA)
    description: SuperTokens supports two-factor authentication, adding an extra
      layer of security to user accounts.
  - title: Single sign-on (SSO)
    description: SuperTokens offers single sign-on functionality, allowing users to
      log in to multiple applications with a single set of credentials.
  - title: Session management
    description: SuperTokens provides session management features, allowing
      developers to manage user sessions and control session expiration.
  - title: User management
    description: SuperTokens offers user management capabilities, allowing
      developers to create, update, and delete user accounts.
  - title: Account linking
    description: SuperTokens supports account linking, allowing users to link
      multiple accounts and log in using any of the linked accounts.
  - title: Multi-tenant SSO
    description: SuperTokens supports multi-tenant single sign-on, allowing
      developers to configure sign-up with Okta, Microsoft AD, and SAML per
      customer.
  - title: Extensive documentation and resources
    description: SuperTokens provides comprehensive documentation, guides,
      implementation recipes, and API references to help developers get started
      and integrate SuperTokens into their applications.
  - title: Trusted by startups and enterprises
    description: SuperTokens is trusted by startups and enterprises alike, providing
      a reliable and secure authentication solution for businesses of all sizes.
  - title: Hosted solutions or frontend SDKs
    description: SuperTokens offers hosted solutions on your own domain, eliminating
      the need for redirects. Alternatively, developers can use SuperTokens'
      frontend SDKs and helper functions to build their own login page quickly.
  - title: Open-source and community-driven
    description: SuperTokens is an open-source project with a large community of
      contributors. It is backed by Y-Combinator and has raised $300 million in
      funding.
  - title: Responsive support and quick response time
    description: SuperTokens has a responsive support team that answers user
      requests within 5 minutes during business hours. The company has a strong
      focus on customer satisfaction and provides 99.9% uptime.
