name: Wizarr
description: Wizarr is an automatic user invitation system for Plex, Jellyfin,
  and Emby. It allows you to create a unique link and share it with users, who
  will automatically be invited to your media server. Wizarr also provides
  instructions on how to download the clients and use your requests software. It
  supports single-sign-on (SSO), multi-tiered invitations, and integration with
  Discord and requests software.
instructions: null
changeLog:
  - date: 2023-03-1
    description: first release
  - date: 2023-03-22
    description: Update to v2.1.3
links:
  - label: Documentation
    url: https://docs.wizarr.dev
  - label: Github
    url: https://github.com/Wizarrrr/wizarr
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: wizarr
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/wizarrrr/wizarr:2.1.3
tags:
  - Media
  - Developer Tools
benefits:
  - title: Automatic Invitation
    description: Wizarr automatically invites users to your media server when they
      click on the unique link.
  - title: Secured Invitation Environment
    description: Wizarr provides a secure environment for user invitations.
  - title: Plug and Play SSO Support
    description: Wizarr supports single-sign-on (SSO) for easy user authentication.
  - title: Multi-tiered Invitations
    description: Wizarr allows you to create invitations with different membership tiers.
  - title: Guide User on Downloading Plex Client
    description: Wizarr provides instructions on how to download the Plex client.
  - title: Requests Integration
    description: Wizarr integrates with requests software (Jellyseerr, Overseerr,
      Ombi) to guide users on how to request movies.
  - title: Discord Server Integration
    description: Wizarr integrates with Discord to invite users to your Discord server.
  - title: Customizable
    description: Wizarr allows you to add custom HTML to personalize the user experience.
features:
  - title: Automatic Invitation to your Media Server
    description: Wizarr automatically invites users to your media server (Plex,
      Jellyfin, Emby) when they click on the unique link.
  - title: Secured Invitation Environment
    description: Wizarr provides a secure environment for user invitations.
  - title: Plug and Play SSO Support
    description: Wizarr supports single-sign-on (SSO) for easy user authentication.
  - title: Multi-tiered Invitations
    description: Wizarr allows you to create invitations with different membership tiers.
  - title: Duration for Membership
    description: Wizarr allows you to set a duration for user memberships.
  - title: Guide User on Downloading Plex Client
    description: Wizarr provides instructions on how to download the Plex client.
  - title: Requests Integration
    description: Wizarr integrates with requests software (Jellyseerr, Overseerr,
      Ombi) to guide users on how to request movies.
  - title: Discord Server Integration
    description: Wizarr integrates with Discord to invite users to your Discord server.
  - title: Customizable
    description: Wizarr allows you to add custom HTML to personalize the user experience.
