name: Lenpaste
description: Lenpaste is an open-source web service that allows users to share
  notes anonymously. It is an alternative to pastebin.com and offers its own
  API. The service supports multiple languages, does not require registration,
  and uses cookies only to store settings. It can also work without JavaScript.
  Lenpaste is self-hosted and has a public servers list where users can find and
  add their own servers.
instructions: null
changeLog:
  - date: 2023-1-28
    description: update to v1.3
  - date: 2022-12-20
    description: first release
links:
  - label: Documentation
    url: https://git.lcomrade.su/root/lenpaste/src/branch/main/docs
  - label: Gitea
    url: https://git.lcomrade.su/root/lenpaste
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
  - name: Leonid Maslakov
    url: https://lcomrade.su
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: lenpaste
    appServiceImage:
      type: string
      title: App Service Image
      default: git.lcomrade.su/root/lenpaste:1.3
tags:
  - Notes
  - Web Hosting
benefits:
  - title: No registration required
    description: Users can start sharing notes immediately without the need to
      create an account.
  - title: Supports multiple languages
    description: Lenpaste supports sharing notes in multiple programming languages
      and text formats.
  - title: Self-hosted
    description: Users have the option to host their own Lenpaste server, giving
      them full control over their data.
  - title: Open-source
    description: Lenpaste is an open-source project, allowing users to contribute to
      its development and customize it to their needs.
  - title: API available
    description: Lenpaste provides its own API, allowing developers to integrate it
      into their applications or services.
features:
  - title: No registration
    description: Users can start sharing notes immediately without the need to
      create an account.
  - title: Multiple languages
    description: Supports sharing notes in multiple programming languages and text formats.
  - title: Self-hosted
    description: Users have the option to host their own Lenpaste server, giving
      them full control over their data.
  - title: Open-source
    description: Lenpaste is an open-source project, allowing users to contribute to
      its development and customize it to their needs.
  - title: API
    description: Lenpaste provides its own API, allowing developers to integrate it
      into their applications or services.
