name: Strapi
description: Strapi is an open-source headless CMS that allows developers to
  build customizable content APIs and use them with a modern tech stack. It
  offers a flexible data structure, easy content management, and the ability to
  integrate with various frameworks and tools. Strapi can be deployed on Strapi
  Cloud or on any cloud platform, giving users control and no vendor lock-in.
instructions: null
changeLog:
  - date: 2022-07-12
    description: first release
links:
  - label: Website
    url: https://strapi.io/
  - label: Documentation
    url: https://docs.strapi.io/developer-docs/latest/getting-started/introduction.html
  - label: Github
    url: https://github.com/strapi
contributors:
  - name: Ponkhy
    url: https://github.com/Ponkhy
  - name: Andrei Canta
    url: https://github.com/deiucanta
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseType
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: strapi
    appServiceImage:
      type: string
      title: App Service Image
      default: strapi/strapi:3.6.8-alpine
    databaseType:
      type: string
      title: Database Type
      default: sqlite
      oneOf:
        - enum:
            - sqlite
          title: SQLite
        - enum:
            - postgres
          title: Postgres
        - enum:
            - mariadb
          title: MariaDB
    databaseServiceName:
      type: string
      title: Database Service Name
      default: strapi-db
tags:
  - CMS
  - Developer Tools
benefits:
  - title: Build apps fast
    description: Get your backend done in minutes instead of weeks. Easily build
      customizable content API and use them with a modern tech stack.
  - title: Open Source Forever
    description: The entire codebase is available on GitHub and maintained by
      hundreds of contributors.
  - title: Customizable
    description: Easily customize the admin panel as well as the API. Extend your
      content management with custom plugins, in seconds.
  - title: RESTful or GraphQL
    description: Consume the API from any client (React, Vue, Angular), mobile apps
      or even IoT devices, using REST or GraphQL.
  - title: Self-hosted or Cloud
    description: Extend the capabilities of Strapi with Strapi Cloud, our fully
      managed platform or deploy on-premises, on your favorite public cloud or
      the PaaS of your choice. You’re in control, no lock-in.
features:
  - title: Effortlessly create content structures
    description: Define models and add relations to create rich layout experiences.
  - title: Seamlessly write, edit and manage any content types
    description: Deliver content faster no matter your industries, use cases,
      locations, devices, and channels.
  - title: Easily build apps and digital experiences
    description: Integrate individual best-in-class services by third-party vendors
      and connect any framework of your choice.
  - title: Consume Strapi API from any client
    description: Use a standard RESTful API or GraphQL to query your content.
  - title: Deploy on Strapi Cloud or on any cloud platforms
    description: Strapi can be deployed on Strapi Cloud or on services such as
      21YunBox, Render, AWS, Azure, and others or locally using Docker.
