name: pgvector
description: Open-source vector similarity search for Postgres
instructions: null
changeLog:
  - date: 2023-06-30
    description: first release
links:
  - label: Github
    url: https://github.com/pgvector/pgvector
contributors:
  - name: AlexSerban
    url: https://github.com/serban-alexandru
schema:
  type: object
  required:
    - projectName
    - serviceName
    - serviceImage
  properties:
    projectName:
      type: string
      title: Project Name
    serviceName:
      type: string
      title: Service Name
    serviceImage:
      type: string
      title: Service Image
      default: ankane/pgvector:v0.4.4
