name: HumHub
description: HumHub is a free social network software and framework that allows
  you to create your own customized social network, social intranet, or
  enterprise application. It is lightweight, powerful, and user-friendly. With
  HumHub, you can communicate and collaborate with others, create spaces for
  different projects or groups, extend your profile, and customize the platform
  according to your needs. It is open-source, flexible, and secure, giving you
  full control over your data. HumHub also offers professional services and
  support for your projects.
instructions: null
changeLog:
  - date: 2023-1-22
    description: first release
links:
  - label: Website
    url: https://www.humhub.com
  - label: Documentation
    url: http://docs.humhub.org/
  - label: Github
    url: https://github.com/humhub/humhub/
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: humhub
    appServiceImage:
      type: string
      title: App Service Image
      default: mriedmann/humhub:1.13.0
    databaseServiceName:
      type: string
      title: Database Service Name
      default: humhub-db
tags:
  - Social Networking
  - CMS
benefits:
  - title: Open Source
    description: HumHub is completely open-source, allowing you to take advantage of
      the work already done and even improve it. Every suggestion or help is
      welcome.
  - title: Flexible
    description: With a powerful module system, you can extend HumHub by using
      third-party tools, writing your own modules, or connecting existing
      software.
  - title: Secure
    description: HumHub is a self-hosted solution, which means you have full control
      over your server and data. Your data is secure and protected.
  - title: Services
    description: HumHub provides professional services and support for your
      projects. They don't leave you alone and help you with your HumHub
      implementation.
features:
  - title: Social Communication
    description: Communicate like you already do in other social networks, but with
      your own rules. Write posts, share files, like and comment just the way
      you want it.
  - title: Spaces
    description: The communication in HumHub works with spaces. A space can be a
      project, a group, or a topic. You can invite multiple users to a space and
      define access rights and rules.
  - title: Profile Customization
    description: Extend your profile, create your portfolio, connect with other
      people, find the right person with special skills, and inform your
      followers with updates on your own wall.
  - title: Unlimited Possibilities
    description: With modules, you can modify anything on HumHub according to your
      requirements. You can build anything you are missing on other social
      networks.
  - title: Notifications
    description: Stay well-informed about things related to you with notifications.
  - title: Activity Stream
    description: Monitor work and communications at a glance with the activity stream.
  - title: Dashboard
    description: Get an overview and fast access to the most important information
      with the dashboard.
  - title: Social Tools
    description: Post, comment, follow, like, and connect with other users using
      social tools.
  - title: User Profiles
    description: Each user has a digital business card, which can be customized and
      used to showcase skills and connect with others.
  - title: Groups
    description: Organize users in departments, branches, or any other groups for
      better collaboration and communication.
  - title: Directory
    description: Easily find spaces, users, and groups in a sorted way using the directory.
  - title: File Sharing
    description: Share documents and media files with others and discuss them within
      the platform.
  - title: Public Access
    description: Share content with non-registered users, allowing them to access
      and view the content.
  - title: Search
    description: Find people, discussions, and files easily using the search feature.
  - title: Mobile Ready
    description: HumHub is compatible with all kinds of modern devices like
      smartphones and tablets, allowing you to access and use it on the go.
