name: Windmill
description: Windmill is an app development platform that allows you to easily
  create internal apps and workflows with code only where it matters. It
  provides a self-hostable worker infrastructure that is scalable, reliable, and
  fast. Windmill is a fully open-source alternative to Airplane, Superblocks,
  and Retool.
instructions: Login using admin@windmill.dev:changeme
changeLog:
  - date: 2023-03-1
    description: first release
  - date: 2023-03-22
    description: Update to v.1.80.1
  - date: 2023-05-25
    description: Update to latest + EE
links:
  - label: Website
    url: https://windmill.dev
  - label: Documentation
    url: https://docs.windmill.dev
  - label: Github
    url: https://github.com/windmill-labs/windmill
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: windmill
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/windmill-labs/windmill:main
    licenseKey:
      type: string
      title: EE License Key
    databaseServiceName:
      type: string
      title: Database Service Name
      default: windmill-db
tags:
  - Developer Tools
  - Productivity
benefits:
  - title: Turn scripts into workflows and UIs in minutes
    description: With Windmill, you can turn your scripts into workflows and user
      interfaces (UIs) in just minutes. This allows you to create internal apps
      and invincible workflows without the need for extensive coding.
  - title: Superpowers for your scripts
    description: Windmill gives your scripts superpowers by making them
      production-grade. You can build all of your internal tools with Python,
      Typescript, Go, Bash, and SQL. Windmill also allows you to compose your
      scripts as workflows using low-code, and provides an autogenerated UI or
      the option to build one using low-code.
  - title: Scalable, reliable, and fast infrastructure
    description: Windmill provides a self-hostable worker infrastructure that is
      scalable, reliable, and fast. You can run your scripts and workflows
      reliably at scale on your own infrastructure or on Windmill's
      infrastructure. Windmill also includes permissioning and monitoring
      features.
features:
  - title: Polyglot scripting
    description: Windmill supports multiple scripting languages including
      Typescript, Python, Go, Bash, and SQL. You can choose the language that
      best suits your needs for building scripts and workflows.
  - title: Autogenerated UI and dependencies
    description: Windmill automatically generates a user interface (UI) for your
      scripts and workflows. It also handles dependencies with zero
      configuration, making it easy to manage and run your scripts.
  - title: Flows for complex workflows
    description: Windmill allows you to build complex workflows using atomic
      scripts. You can create branching logic, for loops, and error handlers to
      handle complex scenarios in your workflows.
  - title: Build powerful apps with drag and drop
    description: Windmill provides an app editor that allows you to build powerful
      apps using drag and drop components. You can connect your data, deploy
      your app in minutes, and run any script or workflow from the app editor.
  - title: Fast and performant
    description: Windmill is designed to be fast and performant. It offers instant
      preview and execution, live logs, and a reactive engine that ensures your
      apps are always super performant, even when running complex workflows.
  - title: Enterprise-ready platform
    description: Windmill is an enterprise-ready platform with features like audit
      logs, role-based access control (RBAC), scalability, and air-gapped
      deployment. It is also open-source, allowing you to contribute to its
      development.
