name: Verdaccio
description: Verdaccio is a lightweight private npm proxy registry built in
  Node.js. It provides a compatible API with npm clients and supports semantic
  versioning. Verdaccio is a web app based on Node.js that acts as a private npm
  registry and a local network proxy. It is easy to install and use, and offers
  Docker and Kubernetes support. It is 100% compatible with yarn, npm, and pnpm.
instructions: null
changeLog:
  - date: 2022-10-31
    description: first release
links:
  - label: Website
    url: https://verdaccio.org/
  - label: Documentation
    url: https://verdaccio.org/docs/what-is-verdaccio
  - label: Github
    url: https://github.com/verdaccio/verdaccio
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: verdaccio
    appServiceImage:
      type: string
      title: App Service Image
      default: verdaccio/verdaccio:5.19.1
tags:
  - Developer Tools
  - Networking
benefits:
  - title: Use private packages
    description: Verdaccio allows you to use private packages in your company
      without sending the code to the public. You can use your private packages
      just as easily as public ones.
  - title: Link multiple registries
    description: If you use multiple registries in your organization and need to
      fetch packages from multiple sources in one project, you can chain
      multiple registries and fetch from a single endpoint.
  - title: Cache npmjs.org registry
    description: Verdaccio can cache the npmjs.org registry, reducing latency and
      providing limited failover if you have multiple servers from which you
      want to install packages.
  - title: Override public packages
    description: If you want to use a modified version of a 3rd-party package, you
      can publish your version locally under the same name.
features:
  - title: Private npm proxy registry
    description: Verdaccio acts as a private npm registry, allowing you to publish
      and access private packages.
  - title: Local network proxy
    description: Verdaccio can act as a proxy for other registries, such as
      npmjs.org, and cache downloaded modules to decrease latency and provide
      failover.
  - title: Pluggable application
    description: Verdaccio supports various community-made plugins to extend its
      storage capabilities, such as integrating with Amazon's S3 or Google Cloud
      Storage.
  - title: Easy to install and use
    description: Verdaccio comes with its own tiny database and requires no
      configuration to get started. It is compatible with popular npm clients
      like npm, yarn, and pnpm.
  - title: Docker and Kubernetes support
    description: Verdaccio provides an official Docker image and supports deployment
      using Kubernetes Helm for easy DevOps integration.
