name: SerpBear
description: SerpBear is an Open Source Search Engine Position Tracking App. It allows you to track your website's keyword positions in Google and get notified of their positions.
instructions: null
changeLog:
  - date: 2023-1-5
    description: first release
links:
  - label: Documentation
    url: https://docs.serpbear.com
  - label: Github
    url: https://github.com/towfiqi/serpbear
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - serpUser
    - serpPass
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: serpbear
    appServiceImage:
      type: string
      title: App Service Image
      default: towfiqi/serpbear
    serpUser:
      type: string
      title: Username
    serpPass:
      type: string
      title: Password
tags:
  - Analytics
  - SEO
benefits:
  - title: Unlimited Keywords
    description: Add unlimited domains and unlimited keywords to track their SERP.
  - title: Email Notification
    description: Get notified of your keyword position changes daily/weekly/monthly
      through email.
  - title: SERP API
    description: SerpBear comes with built-in API that you can use for your
      marketing & data reporting tools.
  - title: Google Search Console Integration
    description: Get the actual visit count, impressions & more for each keyword.
  - title: Mobile App
    description: Add the PWA app to your mobile for a better mobile experience.
  - title: Zero Cost to RUN
    description: Run the App on mogenius.com or Fly.io for free.
features:
  - title: Unlimited Keywords
    description: Add unlimited domains and unlimited keywords to track their SERP.
  - title: Email Notification
    description: Get notified of your keyword position changes daily/weekly/monthly
      through email.
  - title: SERP API
    description: SerpBear comes with built-in API that you can use for your
      marketing & data reporting tools.
  - title: Google Search Console Integration
    description: Get the actual visit count, impressions & more for each keyword.
  - title: Mobile App
    description: Add the PWA app to your mobile for a better mobile experience.
  - title: Zero Cost to RUN
    description: Run the App on mogenius.com or Fly.io for free.
