name: Lychee
description: Lychee is a free photo-management tool that allows you to upload,
  manage, and share photos from your server or web-space. It provides a
  user-friendly interface and supports features like batch editing, EXIF and
  IPTC metadata, and importing photos from various sources. Lychee is
  open-source, secure, and designed for photographers.
instructions: Lychee takes a few minutes to get ready. Sit back, relax, and have a coffee!
changeLog:
  - date: 2022-10-28
    description: first release
links:
  - label: Website
    url: https://lycheeorg.github.io/
  - label: Documentation
    url: https://lycheeorg.github.io/docs/
  - label: Github
    url: https://github.com/LycheeOrg/Lychee
  - label: Demo
    url: https://lycheeorg.github.io/demo/
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseType
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: lychee
    appServiceImage:
      type: string
      title: App Service Image
      default: lycheeorg/lychee:v4.7.4
    databaseType:
      type: string
      title: Database Type
      default: sqlite
      oneOf:
        - enum:
            - sqlite
          title: SQLite
tags:
  - File Management
  - Media
benefits:
  - title: Self-hosted Solution
    description: Lychee is a self-hosted solution, which means you have full control
      over your server and data. You don't have to depend on any third-party
      service.
  - title: Intuitive Interface
    description: Lychee has a stunning and beautiful interface that is easy to use.
      It is designed to be user-friendly and accessible to everyone.
  - title: No Storage Limit
    description: Lychee allows you to store unlimited photos without any storage
      limit. Your photos are stored securely and can be accessed anytime.
  - title: Batch Editing
    description: With Lychee, you can perform batch editing on your photos. You can
      select multiple photos and apply changes like renaming, tagging, or
      deleting in one go.
  - title: Share and Protect
    description: Lychee makes it easy to share your photos with others. You can
      create public albums or protect them with passwords for privacy.
features:
  - title: Upload and Manage
    description: Easily upload your photos or create new albums. Manage your photos
      by moving, renaming, describing, deleting, or searching them.
  - title: View and Navigate
    description: View your photos in full-screen mode and navigate through them
      using your keyboard. Make your photos public to let others enjoy them.
  - title: EXIF and IPTC Metadata
    description: Lychee supports EXIF and IPTC metadata, allowing you to get the
      most out of your photos. The metadata is clearly listed next to other
      information.
  - title: Import from Various Sources
    description: Import your photos from different sources, including your local
      computer, server, URL, or Dropbox. Lychee makes it easy to bring all your
      photos together.
  - title: Open-Source and Customizable
    description: Lychee is an open-source project, which means anyone can contribute
      to its development and improvement. You can customize it according to your
      needs.
