name: Freshrss
description: Freshrss is a free, self-hostable aggregator for rss feeds.
instructions: null
changeLog:
  - date: 2022-11-14
    description: first release
links:
  - label: Documentation
    url: https://docs.linuxserver.io/images/docker-freshrss
  - label: Github
    url: https://github.com/linuxserver/docker-freshrss
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: freshrss
    appServiceImage:
      type: string
      title: App Service Image
      default: lscr.io/linuxserver/freshrss:latest
tags:
  - RSS
  - Web Hosting
benefits:
  - title: Self-hosted
    description: You have full control over your data and can customize the
      application to your needs.
  - title: Multi-platform support
    description: The Docker image supports multiple architectures, making it easy to
      run on different systems.
  - title: Easy setup
    description: The application can be set up quickly using either docker-compose
      or the docker CLI.
features:
  - title: WebUI
    description: Access the application through a web interface.
  - title: External database support
    description: You can use an external MySQL/MariaDB server for storing data.
  - title: Extensions support
    description: Additional extensions can be added to enhance the functionality of
      the application.
