name: imgproxy
description: imgproxy is an app that optimizes images for the web on the fly. It
  makes websites and apps blazing fast while saving storage and SaaS costs.
instructions: "To generate a image URL you can use the following link:
  https://progapandist.github.io/imgproxy-form/#. Your Salt and Key can be found
  in the environment variables once you create the service. You can also find
  more environment variables here: https://docs.imgproxy.net/configuration"
changeLog:
  - date: 2022-08-05
    description: first release
links:
  - label: Website
    url: https://imgproxy.net/
  - label: Documentation
    url: https://docs.imgproxy.net/
  - label: Github
    url: https://www.github.com/imgproxy/imgproxy
contributors:
  - name: Ivan Ryan
    url: https://github.com/ivanonpc-22
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: imgproxy
    appServiceImage:
      type: string
      title: App Service Image
      default: darthsim/imgproxy:v3.13.2
tags:
  - Developer Tools
  - Media
benefits:
  - title: Blazing Fast Performance
    description: imgproxy resizes and processes images on the fly, resulting in
      faster loading times for websites and apps.
  - title: Cost Savings
    description: By optimizing images on the fly, imgproxy helps save storage and
      SaaS costs by avoiding the need to store multiple versions of the same
      image.
features:
  - title: Resize Images
    description: imgproxy allows you to resize images to specific dimensions.
  - title: Crop Pictures
    description: Crop pictures to focus on specific areas or remove unwanted parts.
  - title: Add Watermarks
    description: Add custom watermarks to images to protect your content.
  - title: Image Filters
    description: Apply various filters to images, such as contrast, pixelization,
      saturation, and more.
  - title: Security Features
    description: imgproxy includes security features to protect against image bombs,
      URL signing, and authorization.
