name: Nzbget
description: NZBGet is an efficient Usenet downloader that allows users to
  download files from Usenet based on information given in nzb-files. It is
  known for its performance and efficiency, and can run on almost any device
  including PCs, NAS, media players, SAT-receivers, and WLAN-routers. NZBGet is
  open source and hosted on GitHub.
instructions: null
changeLog:
  - date: 2022-07-12
    description: first release
links:
  - label: Website
    url: https://nzbget.net/
  - label: Documentation
    url: https://nzbget.net/documentation
  - label: Github
    url: https://github.com/nzbget/nzbget
contributors:
  - name: Ponkhy
    url: https://github.com/Ponkhy
  - name: Andrei Canta
    url: https://github.com/deiucanta
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - username
    - password
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: nzbget
    appServiceImage:
      type: string
      title: App Service Image
      default: lscr.io/linuxserver/nzbget:21.1.20220922
    username:
      type: string
      title: Username
      default: nzbget
    password:
      type: string
      title: Password
      default: tegbzn6789
    serviceTimezone:
      type: string
      title: Timezone
      default: Europe/London
tags:
  - File Management
  - Developer Tools
benefits:
  - title: Efficient Downloading
    description: NZBGet is designed to be highly efficient, allowing users to
      download files from Usenet quickly and easily.
  - title: Cross-Platform Compatibility
    description: NZBGet can run on almost any device, including Windows, Mac, Linux,
      BSD, and Android.
  - title: Open Source
    description: NZBGet is an open source project hosted on GitHub, allowing users
      to contribute to its development and customization.
features:
  - title: Installation Manuals
    description: NZBGet provides detailed installation manuals for various
      platforms, including Windows, Mac, Linux, FreeBSD, and Android.
  - title: Configuration
    description: NZBGet offers a range of configuration options to customize the
      downloading process and optimize performance.
  - title: Automation
    description: NZBGet supports automation features such as RSS and duplicate
      check, allowing users to automate their downloads with RSS feeds.
  - title: Post-Processing
    description: NZBGet provides post-processing scripts for sorting downloaded
      video files and performing other tasks after the download is complete.
  - title: API
    description: NZBGet offers an API that allows communication with the application
      from other applications or scripts.
