name: Restreamer
description: datarhei Restreamer is a real-time live video streaming platform
  that allows teams to stream and restream video on websites and social media
  platforms without additional streaming provider costs or software licensing
  costs. It can be installed on a Raspberry Pi and supports various streaming
  protocols.
instructions: null
changeLog:
  - date: 2022-10-29
    description: first release
  - date: 2023-05-08
    description: Upgraded to version 2.6.0.
links:
  - label: Documentation
    url: https://docs.datarhei.com/restreamer/
  - label: Github
    url: https://github.com/datarhei/restreamer
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
  - name: Berk Sümbül
    url: https://berksmbl.com
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: restreamer
    appServiceImage:
      type: string
      title: App Service Image
      default: datarhei/restreamer:2.4.2
tags:
  - "Streaming "
  - Web Hosting
benefits:
  - title: Cost-effective
    description: Eliminates the need for additional streaming provider costs and
      software licensing costs.
  - title: Easy to use
    description: Provides a simple yet powerful service for teams to live stream video.
  - title: Flexible installation
    description: Can be installed on a Raspberry Pi or other hardware as long as
      Docker is available.
features:
  - title: Live streaming on websites
    description: Allows live streaming on websites without additional service
      providers or video hosting providers.
  - title: Publication services
    description: Enables sharing live videos publicly or privately with anyone, or
      using a secret link to give access to private content.
  - title: API integration
    description: Provides a fully documented API for easy software development and
      integration.
