name: phpMyAdmin
description: phpMyAdmin is a free software tool written in PHP, intended to
  handle the administration of MySQL over the Web. It supports a wide range of
  operations on MySQL and MariaDB, including managing databases, tables,
  columns, relations, indexes, users, permissions, etc. Users can perform these
  operations via the user interface or directly execute SQL statements.
  phpMyAdmin comes with extensive documentation and support channels to help
  users. It is available in 72 languages and supports both LTR and RTL
  languages. phpMyAdmin is a mature project with a stable and flexible code
  base. It is a member of Software Freedom Conservancy, a not-for-profit
  organization that promotes and defends Free, Libre, and Open Source Software
  (FLOSS) projects.
instructions: null
changeLog:
  - date: 2022-07-12
    description: first release
links:
  - label: Website
    url: https://www.phpmyadmin.net/
  - label: Documentation
    url: https://www.phpmyadmin.net/docs/
  - label: Github
    url: https://github.com/phpmyadmin/phpmyadmin
contributors:
  - name: Andrei Canta
    url: https://github.com/deiucanta
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: phpmyadmin
    appServiceImage:
      type: string
      title: App Service Image
      default: phpmyadmin:5.2.0
tags:
  - Database
  - CMS
benefits:
  - title: Easy Administration
    description: phpMyAdmin provides an intuitive web interface for managing MySQL
      and MariaDB databases. Users can easily perform common operations such as
      creating, copying, dropping, renaming, and altering databases, tables,
      fields, and indexes.
  - title: SQL Execution
    description: phpMyAdmin allows users to execute and edit SQL statements
      directly. Users can also bookmark SQL statements and execute batch
      queries.
  - title: User Account Management
    description: phpMyAdmin provides tools for managing MySQL user accounts and
      privileges. Users can create, edit, and delete user accounts, as well as
      assign permissions.
  - title: Data Import and Export
    description: phpMyAdmin supports importing data from CSV and SQL files, and
      exporting data to various formats including CSV, SQL, XML, PDF, and more.
  - title: Query Building
    description: phpMyAdmin allows users to build complex queries using
      Query-by-example (QBE). Users can search globally in a database or a
      subset of it.
  - title: Data Transformation
    description: phpMyAdmin provides a set of predefined functions for transforming
      stored data into any format. Users can display BLOB-data as an image or
      download-link, among other transformations.
features:
  - title: Intuitive web interface
    description: phpMyAdmin provides an easy-to-use web interface for managing MySQL
      and MariaDB databases.
  - title: Support for most MySQL features
    description: phpMyAdmin supports a wide range of MySQL features, including
      browsing and dropping databases, tables, views, fields, and indexes;
      creating, copying, dropping, renaming, and altering databases, tables,
      fields, and indexes; and more.
  - title: Maintenance server, databases, and tables
    description: phpMyAdmin provides tools for maintaining the server, databases,
      and tables. It also offers proposals on server configuration.
  - title: Execute and edit SQL statements
    description: phpMyAdmin allows users to execute and edit SQL statements
      directly. Users can also bookmark SQL statements and execute batch
      queries.
  - title: Manage MySQL user accounts and privileges
    description: phpMyAdmin provides tools for managing MySQL user accounts and
      privileges. Users can create, edit, and delete user accounts, as well as
      assign permissions.
  - title: Manage stored procedures and triggers
    description: phpMyAdmin allows users to manage stored procedures and triggers in
      MySQL and MariaDB.
  - title: Import and export data
    description: phpMyAdmin supports importing data from CSV and SQL files, and
      exporting data to various formats including CSV, SQL, XML, PDF, and more.
  - title: Administering multiple servers
    description: phpMyAdmin allows users to administer multiple MySQL and MariaDB servers.
  - title: Creating graphics of database layout
    description: phpMyAdmin provides tools for creating graphics of the database
      layout in various formats.
  - title: Creating complex queries using Query-by-example (QBE)
    description: phpMyAdmin allows users to create complex queries using
      Query-by-example (QBE).
  - title: Searching globally in a database
    description: phpMyAdmin allows users to search globally in a database or a subset of it.
  - title: Transforming stored data into any format
    description: phpMyAdmin provides a set of predefined functions for transforming
      stored data into any format. Users can display BLOB-data as an image or
      download-link, among other transformations.
