name: Mattermost
description: Mattermost is a secure collaboration app designed for technical and
  operational teams. It provides a familiar user interface, fast performance,
  and a complete set of user collaboration tools and features. Mattermost offers
  a self-managed installation option for better integration with existing IT
  assets and more control over data storage. It is HIPAA compliant, making it
  suitable for healthcare organizations. With local hosting and simple Docker
  installation, data security compliance is easy to achieve. Mattermost is
  highly customizable and offers flexible integrations, allowing teams to adapt
  the app to their workflow. It is built with stringent security and privacy
  requirements in mind, providing granular admin controls, full control over
  data, advanced compliance auditing and reporting, and options for on-prem and
  secure cloud deployment. Mattermost is trusted by thousands of technical teams
  worldwide and has a large and active community of contributors.
instructions: null
changeLog:
  - date: 2022-07-12
    description: first release
  - date: 2022-10-12
    description: ablity to define custom docker image version
  - date: 2022-11-29
    description: Update mattermost to 7.5.1
  - date: 2023-1-26
    description: Update mattermost to 7.7
links:
  - label: Website
    url: https://mattermost.com/
  - label: Github
    url: https://github.com/mattermost/
contributors:
  - name: Bedeoan Raul
    url: https://github.com/bedeoan
  - name: Andrei Canta
    url: https://github.com/deiucanta
  - name: Peter Fodor
    url: https://github.com/fodurrr
  - name: Supernova3339
    url: https://github.com/supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: mattermost
    appServiceImage:
      type: string
      title: App Service Image
      default: mattermost/mattermost-team-edition:7.10
    databaseServiceName:
      type: string
      title: Database Service Name
      default: mattermost-db
tags:
  - Communication
  - Developer Tools
benefits:
  - title: Secure Collaboration
    description: Give operational and engineering teams the workspace they need to
      collaborate securely and effectively. Improve time to response, decrease
      incident resolution time, and stay compliant with full data control.
  - title: Avoid Costly Outages and Downtime
    description: Save costs by decreasing the frequency and severity of system
      failures and outages.
  - title: Increase Information Availability
    description: Increase information availability by executing complex workflows
      faster at higher quality.
features:
  - title: Team Messaging
    description: Collaborate with your team through secure messaging, file sharing,
      and rich media support.
  - title: Project Management
    description: Manage projects and tasks with built-in project management
      features, including task assignment, progress tracking, and notifications.
  - title: Custom Integrations
    description: Integrate Mattermost with your existing tools and systems to
      streamline workflows and improve productivity.
  - title: Audio & Screen Sharing
    description: Easily communicate with your team through audio and video calls,
      and share your screen for effective collaboration.
  - title: Workflow Automation
    description: Automate repetitive tasks and streamline workflows with custom
      workflows and integrations.
