name: Portainer
description: Portainer is a powerful container management platform that allows
  you to deploy, configure, troubleshoot, and secure containers in minutes. It
  supports Kubernetes, Docker, and Docker Swarm running in any data center,
  cloud, network edge, or IIOT device. With Portainer, you can save time by
  deploying apps rapidly, reduce risk by managing and securing your clusters
  quickly, and minimize complexity with sane defaults to keep your team on the
  right track.
instructions: null
changeLog:
  - date: 2022-07-12
    description: first release
links:
  - label: Website
    url: https://www.portainer.io/
  - label: Documentation
    url: https://docs.portainer.io/
  - label: Github
    url: https://github.com/portainer/portainer#readme
contributors:
  - name: Andrei Canta
    url: https://github.com/deiucanta
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: portainer
    appServiceImage:
      type: string
      title: App Service Image
      default: portainer/portainer-ce:2.15.1-alpine
tags:
  - Containers
  - Dashboard
benefits:
  - title: Save Time
    description: Deploy cloud-native applications into containers simply, quickly,
      and securely.
  - title: Reduce Risk
    description: Manage and secure your clusters quickly to minimize potential risks.
  - title: Minimize Complexity
    description: Sane defaults and intuitive UI to keep your team on the right track.
features:
  - title: Deploy Containers
    description: Helps developers deploy cloud-native applications into containers
      simply, quickly, and securely.
  - title: Troubleshoot Apps
    description: Find out why your application isn’t working and fix it fast with
      the help of Portainer.
  - title: Lifecycle Management
    description: Manage and update your deployments easily with Portainer.
  - title: Platform Management
    description: Set up, maintain, and troubleshoot your container infrastructure with ease.
  - title: Security & Compliance
    description: A powerful policy and governance platform to ensure security and
      compliance.
