name: n8n
description: n8n is a workflow automation tool designed for technical people. It
  allows users to build complex automations without the need to write extensive
  code. With n8n, users can connect APIs, manipulate data, and integrate with
  any app. The platform offers a user-friendly UI and supports JavaScript for
  added flexibility. n8n is highly customizable and can be self-hosted or used
  in the cloud. It offers a wide range of features, including bulk operations,
  independent instances for each environment, and painless debugging. n8n is
  suitable for various use cases, such as customer integrations, SaaS backend
  prototyping, lead automation, and CRM customization. The platform helps save
  time, boost efficiency, and optimize engineering resources. n8n is scalable,
  with the ability to handle 220 workflow executions per second on a single
  instance. It also provides customizable error handling, workflow sharing, and
  over 600 templates to accelerate workflow creation. n8n is available as a
  hosted solution or can be self-hosted using npm or Docker. The platform is
  open source, allowing users to audit, tweak, and fork the codebase. n8n offers
  flexible pricing options, including a free self-hosted version and paid
  packages for cloud usage. The platform has a strong community of over 55,000
  members and provides extensive documentation and support through a forum of
  n8n engineers and community experts.
instructions: null
changeLog:
  - date: 2022-07-12
    description: first release
links:
  - label: Website
    url: https://n8n.io/
  - label: Documentation
    url: https://docs.n8n.io/
  - label: Github
    url: https://github.com/n8n-io/n8n
contributors:
  - name: Ponkhy
    url: https://github.com/Ponkhy
  - name: Andrei Canta
    url: https://github.com/deiucanta
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: n8n
    appServiceImage:
      type: string
      title: App Service Image
      default: n8nio/n8n:0.225.2
tags:
  - Developer Tools
  - Integration
benefits:
  - title: Workflow automation for technical people
    description: n8n enables technical users to build complex automations without
      the need for extensive coding.
  - title: Flexible and user-friendly
    description: n8n offers a user-friendly UI and supports JavaScript for added
      flexibility in workflow creation.
  - title: Customizable and scalable
    description: n8n allows for customization through independent instances, bulk
      operations, and customizable error handling. It is also scalable, with the
      ability to handle 220 workflow executions per second on a single instance.
  - title: Wide range of use cases
    description: n8n can be used for various use cases, including customer
      integrations, SaaS backend prototyping, lead automation, and CRM
      customization.
  - title: Time and resource optimization
    description: n8n helps save time, boost efficiency, and optimize engineering
      resources by automating tasks and reducing manual work.
features:
  - title: Connect APIs with no code
    description: n8n allows users to connect APIs and automate basic tasks without
      the need for extensive coding.
  - title: Build custom scenarios with JavaScript
    description: Users can write vanilla JavaScript to manipulate complex data and
      build custom scenarios.
  - title: Integrate with any app
    description: n8n supports integration with any app, offering over 350 native
      integrations and the ability to create custom integrations.
  - title: Independent instances for each environment
    description: n8n allows for the creation of independent instances for each
      environment, ensuring separation and control.
  - title: Bulk operations
    description: n8n supports bulk operations, allowing users to perform actions on
      multiple items at once.
  - title: Painless debugging
    description: n8n provides a painless debugging experience, making it easier to
      identify and fix issues in workflows.
  - title: Host on your own infrastructure
    description: n8n can be self-hosted, giving users full control over their
      infrastructure and data security.
  - title: Automated API authentication
    description: n8n offers automated API authentication, simplifying the process of
      connecting to APIs.
