name: Wordpress
description: WordPress is an open-source platform that allows users to create
  and manage websites. It offers a wide range of features and customization
  options, making it suitable for businesses, personal blogs, and more. With
  WordPress, users can design their site using blocks, customize the appearance
  with themes and patterns, and add functionality with plugins. The platform is
  built by a global community of contributors and is constantly updated to
  ensure stability and security. Whether you're a beginner or an experienced
  developer, WordPress provides resources and support to help you learn and
  grow. Join the WordPress community and start building your website today!
instructions: null
changeLog:
  - date: 2022-07-12
    description: first release
links:
  - label: Website
    url: https://wordpress.org/
  - label: Documentation
    url: https://learn.wordpress.org
  - label: Github
    url: https://github.com/WordPress/WordPress
contributors:
  - name: Andrei Canta
    url: https://github.com/deiucanta
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseType
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: wordpress
    appServiceImage:
      type: string
      title: App Service Image
      default: wordpress:6
    databaseType:
      type: string
      title: Database Type
      default: mariadb
      oneOf:
        - enum:
            - mariadb
          title: MariaDB
        - enum:
            - mysql
          title: MySQL
    databaseServiceName:
      type: string
      title: Database Service Name
      default: wordpress-db
tags:
  - CMS
  - Web Hosting
benefits:
  - title: Easy to use
    description: WordPress offers an intuitive editing interface and a wide range of
      customization options, making it easy for users of all skill levels to
      create and manage their websites.
  - title: Flexible design
    description: With WordPress, you can design your site exactly the way you want.
      Choose from a variety of themes and patterns, customize colors and fonts,
      and create unique layouts.
  - title: Powerful features
    description: WordPress offers over 55,000 plugins that allow you to add
      functionality to your site. Whether you need a store, mailing list,
      portfolio, or social feed, there's a plugin for that.
  - title: Ownership and control
    description: With WordPress, you own your content, design, and data. You have
      full control over your website and can customize it to suit your needs.
  - title: Stability and security
    description: WordPress is built by a community of experienced developers who are
      committed to keeping the platform stable and secure. Regular updates and
      security measures are implemented to ensure the safety of your website.
features:
  - title: Block-based editing
    description: WordPress uses a block-based editor that allows you to see how your
      site will look in real time as you add, edit, and rearrange content. This
      intuitive editing experience makes it easy to create custom sites.
  - title: Customization options
    description: Choose from a wide variety of themes and patterns to design your
      site. Customize colors, fonts, layouts, and functionality to create a
      unique and personalized website.
  - title: Plugin ecosystem
    description: WordPress offers over 55,000 plugins that allow you to add
      functionality to your site. Whether you need an online store, email
      marketing tools, or social media integration, there's a plugin for that.
  - title: Ownership and control
    description: With WordPress, you own your content, design, and data. You have
      full control over your website and can customize it to suit your needs.
  - title: Stability and security
    description: WordPress is built by a community of experienced developers who are
      committed to keeping the platform stable and secure. Regular updates and
      security measures are implemented to ensure the safety of your website.
