name: Appsmith
description: Appsmith is a platform that allows engineers to build custom
  software on top of their data. It provides intent-based auto-layouts to help
  build responsive apps faster. With Appsmith, technical users can quickly
  build, deploy, and share applications with end-users to run critical business
  operations. It simplifies internal tool development for businesses,
  streamlining operations, automating processes, and integrating multiple apps
  and data. Appsmith offers features such as data integration from any data
  source, drag and drop widgets to build UI, customization and control with
  code, dev-first workflows with git-based version control, and the ability to
  extend existing apps. It also provides security features such as RBAC, audit
  logging, single sign-on, and secure sign-ups and logins. Appsmith is
  open-source, transparent, and community-driven, with a growing partner
  ecosystem and best-in-class support.
instructions: null
changeLog:
  - date: 2022-07-12
    description: first release
links:
  - label: Website
    url: https://www.appsmith.com/
  - label: Documentation
    url: https://docs.appsmith.com/
  - label: Github
    url: https://github.com/appsmithorg/appsmith
contributors:
  - name: Ponkhy
    url: https://github.com/Ponkhy
  - name: Andrei Canta
    url: https://github.com/deiucanta
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: appsmith
    appServiceImage:
      type: string
      title: App Service Image
      default: appsmith/appsmith-ce:v1.9.16
tags:
  - Dashboard
  - Developer Tools
benefits:
  - title: Build custom software on top of data
    description: Appsmith allows engineers to build custom software on top of their
      data, enabling them to create applications tailored to their specific
      needs.
  - title: Streamline operations and automate processes
    description: With Appsmith, businesses can simplify internal tool development,
      streamline operations, and automate processes, leading to increased
      efficiency and productivity.
  - title: Integrate multiple apps and data
    description: Appsmith provides the ability to quickly integrate multiple apps
      and data, allowing businesses to consolidate their tools and streamline
      workflows.
  - title: Enhance legacy apps with new features
    description: Appsmith enables businesses to enhance their legacy apps with new
      features, extending the functionality and lifespan of existing
      applications.
features:
  - title: Data integration
    description: Appsmith allows users to bring in data from any data source,
      including databases, SaaS tools, and GraphQL/REST APIs. Users can query
      their data directly using SQL or the query builder.
  - title: Drag and drop UI builder
    description: Appsmith provides a drag and drop interface with 45+ customizable
      widgets, allowing users to create beautiful and responsive UIs without
      writing code.
  - title: Customization and control with code
    description: Users can write in-line JavaScript or reusable code blocks to
      customize their app's functionality, extend the UI, or add conditional
      logic.
  - title: Dev-first workflows
    description: Appsmith supports git-based version control, allowing users to sync
      their apps to a git repository and use familiar development workflows. It
      also provides a built-in JavaScript editor with autocomplete, multi-line
      editing, debugging, and linting.
  - title: Extend existing apps
    description: Appsmith allows users to extend the functionalities of their
      existing SaaS apps by embedding them with Appsmith. It also provides RBAC,
      audit logging, single sign-on, and authentication integrations for secure
      access.
  - title: Secure self-hosting
    description: Appsmith can be self-hosted for total control, privacy, and
      security. It offers solid 256-bit encryption, TLS-encrypted connections,
      and encrypted credentials.
  - title: Open-source and community-driven
    description: Appsmith is an open-source platform licensed under Apache License
      2.0. It has a thriving developer community, best-in-class support, and a
      growing partner ecosystem.
