name: CodeX Docs
description: CodeX is a team of passionate engineers and designers, unifying
  students, graduates, and other young specialists around the world interested
  in making high-quality open-source projects and getting a priceless experience
  of making full-valued products on a global market. They have developed various
  open-source projects and products in the fields of Media, Social Networks,
  Education, Augmented Reality, and Medicine. They are known for their Editor.js
  API-oriented, block-styled editor for Media, which generates useful
  JSON-output with clear data. They also have other products like Hawk.so, a
  fast and lightweight errors tracking service, Codex.bot, a platform for
  integration of services into messengers, and Codex Notes, a simple and useful
  cross-platform notes application based on Editor.js and Electron. They also
  have products like Capella, CodeX Media, AR Tester, Deeplinker, Stimagebot,
  Capella for macOS, Email provider detector, CodeX Shortcuts, Module
  Dispatcher, Webpack Build Config, SSL certs expire date checker, Kohana
  Aliases, HTML Slacker, Deploy Server, JS Notifier, Hawk PHP Catcher, CodeX
  Special, AJAX Helper, and JS File Transport. CodeX is active on social media
  platforms like Twitter and Instagram.
instructions: View All Configuation on the Docs site - https://docs.codex.so/configuration
changeLog:
  - date: 2023-01-23
    description: First Release
links:
  - label: Website
    url: https://codex.so
  - label: Documentation
    url: https://docs.codex.so
  - label: Github
    url: https://github.com/codex-team/codex.docs
contributors:
  - name: DrMxrcy
    url: https://github.com/DrMxrcy
schema:
  type: object
  required:
    - projectName
    - codexAuthPassword
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    codexAuthPassword:
      type: string
      title: CodeX Auth Password
    appServiceName:
      type: string
      title: App Service Name
      default: codex
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/codex-team/codex.docs:v2.1
    databaseServiceName:
      type: string
      title: Database Service Name
      default: codex-db
tags:
  - Documentation
  - Productivity
benefits:
  - title: Passionate Team
    description: CodeX is a team of passionate engineers and designers who are
      dedicated to creating high-quality open-source projects.
  - title: Global Market
    description: CodeX aims to make full-valued products that can compete in the
      global market.
  - title: Open-Source Projects
    description: CodeX develops various open-source projects in the fields of Media,
      Social Networks, Education, Augmented Reality, and Medicine.
features:
  - title: Editor.js
    description: CodeX has developed Editor.js, an API-oriented, block-styled editor
      for Media. It generates useful JSON-output with clear data.
  - title: Hawk.so
    description: Hawk.so is a fast and lightweight errors tracking service developed
      by CodeX. It supports catchers for JavaScript, Python, PHP, Node.js,
      Swift, Java Android, Kotlin, and Scala.
  - title: Codex.bot
    description: Codex.bot is a platform for integration of services into
      messengers. It supports integration with Telegram and Slack.
  - title: Codex Notes
    description: Codex Notes is a simple and useful cross-platform notes application
      based on Editor.js and Electron.
  - title: Capella
    description: Capella is a cloud service for image storage and delivery. It
      provides a simple API for uploading files and accepting image filters on
      the fly.
  - title: CodeX Media
    description: CodeX Media is an open platform for building UGC-media communities
      around businesses. It can be used for content marketing and creating own
      media projects.
  - title: AR Tester
    description: AR Tester is an application that allows users to test their
      website's layout on devices in Augmented Reality. It is available on the
      AppStore for iPhone 6s, iPhone 7, iPhone SE, iPad Pro, and newer devices
      with iOS11.
  - title: Deeplinker
    description: Deeplinker is a library for creating web links that can open native
      applications.
  - title: Stimagebot
    description: Stimagebot is a Telegram bot that provides a link to an image for
      any Telegram sticker.
  - title: Capella for macOS
    description: Capella for macOS is an app that allows users to take screenshots
      that are instantly uploaded to the cloud.
  - title: Email Provider Detector
    description: Email Provider Detector is a library that can detect the service
      provider name by an email address.
  - title: CodeX Shortcuts
    description: CodeX Shortcuts is a micro-library for dispatching keyboard
      shortcuts in JavaScript.
  - title: Module Dispatcher
    description: Module Dispatcher is a class for frontend modules initialization
      from the DOM without inline scripts.
  - title: Webpack Build Config
    description: Webpack Build Config is a smart frontend build configuration with
      syntax linters, code style checker, and other helpful tools.
  - title: SSL Certs Expire Date Checker
    description: SSL Certs Expire Date Checker is a Python script for checking the
      expiration date of domain certificates. It sends notifications to Telegram
      or Slack when the expiration date is approaching.
  - title: Kohana Aliases
    description: Kohana Aliases is a routing system for URLs that allows for cool
      and customized addresses for different resources.
  - title: HTML Slacker
    description: HTML Slacker is a library that converts HTML to Slack formatted markdown.
  - title: Deploy Server
    description: Deploy Server is a Python script for automatically deploying
      projects when a git branch is updated.
  - title: JS Notifier
    description: JS Notifier is a lightweight notifications and alerts module for websites.
  - title: Hawk PHP Catcher
    description: Hawk PHP Catcher is an exceptions and errors catcher for PHP.
  - title: CodeX Special
    description: CodeX Special is a module for creating high-contrast versions of websites.
  - title: AJAX Helper
    description: AJAX Helper is a library for working with async-aware requests in
      JavaScript.
  - title: JS File Transport
    description: JS File Transport is a module for file uploading via AJAX in JavaScript.
