name: Plausible
description: Plausible is an intuitive, lightweight, and privacy-friendly
  alternative to Google Analytics. It is easy to use and fully compliant with
  GDPR, CCPA, and PECR. Plausible is made and hosted in the EU, powered by
  European-owned cloud infrastructure. With Plausible, you can get all the
  essential insights about your website traffic on one page in one minute. The
  analytics script is lightweight, resulting in faster site speed and reduced
  carbon footprint. Plausible is privacy-friendly, with no cookies or personal
  data collection. It is useful for tracking goal conversions, revenue, and
  campaigns. You can invite team members and share your dashboard. Plausible is
  transparent and fully open source, with the source code available on GitHub.
  It offers a smooth transition from Universal Analytics and provides a realtime
  dashboard, entry pages report, and integration with Search Console. Plausible
  is trusted by over 10,000 paying subscribers and has been adopted by thousands
  of sites, startups, and leading brands. It operates on a sustainable
  subscription business model and is completely independent, self-funded,
  bootstrapped, and debt-free.
instructions: null
changeLog:
  - date: 2023-1-5
    description: first release
links:
  - label: Website
    url: https://plausible.io
  - label: Documentation
    url: https://plausible.io/docs
  - label: Github
    url: https://github.com/plausible/plausible
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
  - name: Derock
    url: https://github.com/ItzDerock
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
    - clickhouseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: plausible
    appServiceImage:
      type: string
      title: App Service Image
      default: plausible/analytics:v1.5.1
    databaseServiceName:
      type: string
      title: Database Service Name
      default: plausible-db
    clickhouseServiceName:
      type: string
      title: Database Service Name
      default: plausible-clickhouse
tags:
  - Analytics
  - Privacy
benefits:
  - title: Easy to use and privacy-friendly
    description: Plausible is intuitive and easy to understand. It cuts through the
      noise and provides all the essential insights on one page in one minute.
      It is fully compliant with GDPR, CCPA, and PECR, and does not use cookies
      or collect personal data.
  - title: Lightweight script for fast site speed
    description: Plausible's analytics script is 45 times smaller than Google
      Analytics, resulting in faster site speed. By switching to Plausible, you
      can reduce your carbon footprint and contribute to a greener and more
      sustainable web.
  - title: Privacy-friendly analytics
    description: Plausible carries out site measurement anonymously, without the use
      of cookies or persistent identifiers. It does not engage in cross-site or
      cross-device tracking. All visitor data is processed exclusively with
      servers owned and operated by European companies, ensuring data privacy.
  - title: Track goal conversions, revenue, and campaigns
    description: Plausible allows you to segment your audience by any metric and
      answer important questions about your visitors, content, and referral
      sources. You can track goal conversions, revenue, outbound link clicks,
      file downloads, and 404 error pages. Custom events with custom dimensions
      can be created to track conversions and attribution. Funnel analysis helps
      increase conversions.
  - title: Invite team members and share your dashboard
    description: Plausible provides the option to share your stats publicly or
      privately with team members. You can embed the dashboard into your website
      and generate secure links for private sharing. User roles can be assigned
      to team members.
  - title: Transparent and fully open source software
    description: Plausible is open source, with its source code available on GitHub.
      This allows anyone to read, inspect, and review the code for transparency
      and verification. Plausible welcomes feedback and has a public roadmap.
      Self-hosting is also possible for those who prefer to manage their own
      infrastructure.
  - title: Smooth transition from Universal Analytics
    description: Plausible offers a seamless transition from Universal Analytics,
      with features such as a realtime dashboard, entry pages report, and
      integration with Google Search Console. Historical stats can be imported,
      making it easy to switch from Google Analytics.
  - title: Trusted by over 10,000 paying subscribers
    description: Plausible has gained the trust of over 10,000 paying subscribers,
      including thousands of sites, startups, and leading brands. It is a
      reliable and proven alternative to Google Analytics and other analytics
      services.
  - title: Independent, self-funded, and sustainable
    description: Plausible is completely independent, self-funded, bootstrapped, and
      debt-free. It operates on a sustainable subscription business model, with
      fees from subscribers being the sole source of funding. Plausible
      prioritizes user privacy and experience over surveillance capitalism.
features:
  - title: Simple analytics at a glance
    description: Plausible provides simple analytics that are easy to understand.
      All the essential insights about your site traffic can be viewed on one
      page in one minute. There is no need to build custom reports or
      dashboards.
  - title: Lightweight script for fast site speed
    description: Plausible's analytics script is 45 times smaller than Google
      Analytics, resulting in faster site speed. By using Plausible, you can
      reduce your page weight and contribute to a greener and more sustainable
      web.
  - title: No need for cookie banners or GDPR consent
    description: Plausible is privacy-friendly and does not require the use of
      cookie banners or GDPR consent. All site measurement is carried out
      anonymously, without the collection of personal data or the use of
      persistent identifiers.
  - title: Track goal conversions, revenue, and campaigns
    description: Plausible allows you to track goal conversions, revenue, outbound
      link clicks, file downloads, and 404 error pages. You can analyze paid
      campaigns using UTM parameters and create custom events with custom
      dimensions for conversions and attribution. Funnel analysis helps increase
      conversions.
  - title: Invite team members and share your dashboard
    description: Plausible provides the option to invite team members and assign
      user roles. You can share your dashboard publicly or privately with custom
      links. The dashboard can also be embedded into your website.
  - title: Transparent and fully open source software
    description: Plausible is transparent and fully open source. The source code is
      available on GitHub for anyone to read, inspect, and review. Plausible
      welcomes feedback and has a public roadmap. Self-hosting is also possible
      for those who prefer to manage their own infrastructure.
  - title: Smooth transition from Universal Analytics
    description: Plausible offers a seamless transition from Universal Analytics,
      with features such as a realtime dashboard, entry pages report, and
      integration with Google Search Console. Historical stats can be imported,
      making it easy to switch from Google Analytics.
  - title: Trusted by over 10,000 paying subscribers
    description: Plausible has gained the trust of over 10,000 paying subscribers,
      including thousands of sites, startups, and leading brands. It is a
      reliable and proven alternative to Google Analytics and other analytics
      services.
  - title: Independent, self-funded, and sustainable
    description: Plausible is completely independent, self-funded, bootstrapped, and
      debt-free. It operates on a sustainable subscription business model, with
      fees from subscribers being the sole source of funding. Plausible
      prioritizes user privacy and experience over surveillance capitalism.
