name: Node-RED
description: Node-RED is a programming tool for wiring together hardware
  devices, APIs, and online services in new and interesting ways. It provides a
  browser-based editor that makes it easy to wire together flows using the wide
  range of nodes in the palette that can be deployed to its runtime in a
  single-click.
instructions: null
changeLog:
  - date: 2022-10-28
    description: first release
links:
  - label: Website
    url: https://nodered.org/
  - label: Documentation
    url: https://nodered.org/docs/
  - label: Forum
    url: https://discourse.nodered.org/
  - label: Github
    url: https://github.com/node-red
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: nodered
    appServiceImage:
      type: string
      title: App Service Image
      default: nodered/node-red:3.0.2
tags:
  - Developer Tools
  - IoT
benefits:
  - title: Browser-based flow editing
    description: Node-RED provides a browser-based flow editor that makes it easy to
      wire together flows using the wide range of nodes in the palette. Flows
      can be then deployed to the runtime in a single-click. JavaScript
      functions can be created within the editor using a rich text editor. A
      built-in library allows you to save useful functions, templates or flows
      for re-use.
  - title: Built on Node.js
    description: The light-weight runtime is built on Node.js, taking full advantage
      of its event-driven, non-blocking model. This makes it ideal to run at the
      edge of the network on low-cost hardware such as the Raspberry Pi as well
      as in the cloud. With over 225,000 modules in Node's package repository,
      it is easy to extend the range of palette nodes to add new capabilities.
  - title: Social Development
    description: The flows created in Node-RED are stored using JSON which can be
      easily imported and exported for sharing with others. An online flow
      library allows you to share your best flows with the world.
features:
  - title: Browser-based flow editing
    description: Node-RED provides a browser-based flow editor that makes it easy to
      wire together flows using the wide range of nodes in the palette. Flows
      can be then deployed to the runtime in a single-click. JavaScript
      functions can be created within the editor using a rich text editor. A
      built-in library allows you to save useful functions, templates or flows
      for re-use.
  - title: Built on Node.js
    description: The light-weight runtime is built on Node.js, taking full advantage
      of its event-driven, non-blocking model. This makes it ideal to run at the
      edge of the network on low-cost hardware such as the Raspberry Pi as well
      as in the cloud. With over 225,000 modules in Node's package repository,
      it is easy to extend the range of palette nodes to add new capabilities.
