name: Remmina
description: Remmina is a remote desktop client written in GTK, aiming to be useful for system administrators and travellers, who need to work with lots of remote computers in front of either large or tiny screens. Remmina supports multiple network protocols, in an integrated and consistent user interface. Currently RDP, VNC, SPICE, NX, XDMCP, SSH and EXEC are supported.
instructions: use abc:abc to login. To access the login interface, add ?login=true to your URL.
changeLog:
  - date: 2022-11-15
    description: first release
links:
  - label: Documentation
    url: https://docs.linuxserver.io/images/docker-remmina
  - label: Github
    url: https://github.com/linuxserver/docker-remmina
  - label: Website
    url: https://remmina.org
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: remmina
    appServiceImage:
      type: string
      title: App Service Image
      default: lscr.io/linuxserver/remmina:latest
tags:
  - Remote Desktop Client
  - Developer Tools
benefits:
  - title: Multiple network protocols
    description: Remmina supports multiple network protocols, allowing users to
      connect to remote computers using different protocols such as RDP, VNC,
      SPICE, NX, XDMCP, SSH, and EXEC.
  - title: Integrated and consistent user interface
    description: Remmina provides an integrated and consistent user interface,
      making it easy for users to work with remote computers in a seamless
      manner.
  - title: Useful for system administrators and travellers
    description: Remmina is designed to be useful for system administrators and
      travellers who often need to work with multiple remote computers,
      regardless of the screen size.
features:
  - title: Remote desktop client
    description: Remmina is a remote desktop client that allows users to connect to
      and work with remote computers.
  - title: Support for multiple network protocols
    description: Remmina supports multiple network protocols, including RDP, VNC,
      SPICE, NX, XDMCP, SSH, and EXEC.
  - title: Integrated and consistent user interface
    description: Remmina provides an integrated and consistent user interface,
      making it easy for users to work with remote computers.
