name: Actual Budget
description: Actual is a local-first personal finance tool that allows you to
  manage your budget, accounts, and transactions. It is free and open-source,
  written in NodeJS. It has a synchronization feature that allows you to sync
  your changes across devices. Actual also provides documentation for users and
  developers. You can install Actual using npm or use the actual-server project
  for easy setup. The app is split into different packages, including the core
  application, desktop UI, and desktop app. You can also make feature requests
  and vote for existing requests. Actual is sponsored by generous supporters.
instructions: null
changeLog:
  - date: 2023-1-25
    description: first release
links:
  - label: Github
    url: https://github.com/actualbudget/actual
  - label: Documentation
    url: https://actualbudget.github.io/docs
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: actualbudget
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/actualbudget/actual-server:23.2.9
tags:
  - Finance
  - Productivity
benefits:
  - title: Local-first
    description: Actual stores your financial data locally, ensuring privacy and security.
  - title: Sync Across Devices
    description: Changes made in Actual can be synced across multiple devices.
  - title: Free and Open-source
    description: Actual is completely free to use and its source code is available
      for contribution.
features:
  - title: Budgeting
    description: Manage your budget and track your expenses with Actual.
  - title: Account Management
    description: Keep track of your accounts and transactions in Actual.
  - title: Documentation
    description: Actual provides comprehensive documentation for users and developers.
