name: Substreamer
description: Substreamer is a free client app for the Subsonic music server. It
  allows you to access and organize your music library in a personalized way.
  With Substreamer, you can enjoy your music, your way.
instructions: null
changeLog:
  - date: 2023-3-13
    description: first release
links:
  - label: Community
    url: https://reddit.com/substreamer
  - label: Website
    url: https://substreamerapp.com
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: substreamer
    appServiceImage:
      type: string
      title: App Service Image
      default: ghenry22/substreamer:6.0.25
tags:
  - Media
  - Productivity
benefits:
  - title: Your Music, Your Way
    description: Substreamer gives you the freedom to listen to your music library
      in the way that suits you best. Whether you want to create playlists,
      browse by artist or genre, or discover new music, Substreamer has you
      covered.
  - title: Easy Organization
    description: With Substreamer, you can easily organize your music library. You
      can create playlists, add tags to your songs, and even download music for
      offline listening. Say goodbye to the hassle of searching for your
      favorite songs.
  - title: Feature-Packed
    description: Substreamer is packed with features to enhance your music listening
      experience. From gapless playback and crossfade to equalizer settings and
      scrobbling support, Substreamer has everything you need to enjoy your
      music to the fullest.
features:
  - title: Subsonic Server Compatibility
    description: Substreamer works seamlessly with the Subsonic music server,
      allowing you to access your music library from anywhere. It also supports
      Subsonic forks like Airsonic and Madsonic.
  - title: User-Friendly Interface
    description: Substreamer has a user-friendly interface that makes it easy to
      navigate and find your favorite music. The app is designed to be intuitive
      and user-friendly, ensuring a smooth and enjoyable music listening
      experience.
  - title: Free and Open Source
    description: Substreamer is free to use and open source. You can download the
      app for free and customize it to suit your needs. Plus, you can contribute
      to the development of the app and help make it even better.
