name: Wiki.js
description: Wiki.js is a powerful and extensible open source Wiki software that
  makes documentation a joy to write. It can be installed on virtually any
  platform and is compatible with multiple databases. The admin area allows for
  easy management of the wiki, and the performance is optimized with the Node.js
  engine. The appearance of the wiki can be fully customized, and it can be made
  public, private, or a mix of both. Wiki.js is scalable and can be installed on
  a variety of hardware. Installation is quick and easy with step-by-step guides
  available. It also offers a wide range of modules that can be turned on/off as
  needed. Authentication options include built-in authentication, social
  authentication, and enterprise authentication. Two-factor authentication is
  also supported. Wiki.js is open source and has a large number of integrations
  available. It is supported by sponsors and backers, and donations are welcome.
  The official documentation provides detailed information on installation,
  configuration, and usage. Developers can extend Wiki.js with modules, themes,
  and translations.
instructions: null
changeLog:
  - date: 2022-07-12
    description: first release
  - date: 2023-03-22
    description: Update to v2.5.298
links:
  - label: Website
    url: https://js.wiki/
  - label: Documentation
    url: https://docs.requarks.io/
  - label: Github
    url: https://github.com/Requarks/wiki
contributors:
  - name: Andrei Canta
    url: https://github.com/deiucanta
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseType
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: wikijs
    appServiceImage:
      type: string
      title: App Service Image
      default: ghcr.io/requarks/wiki:2.5.298
    databaseType:
      type: string
      title: Database Type
      default: postgres
      oneOf:
        - enum:
            - postgres
          title: Postgres
        - enum:
            - mysql
          title: MySQL
        - enum:
            - mariadb
          title: MariaDB
    databaseServiceName:
      type: string
      title: Database Service Name
      default: wikijs-db
tags:
  - CMS
  - Documentation
benefits:
  - title: Easy Documentation
    description: Wiki.js provides a beautiful and intuitive interface for writing
      documentation, making it a joy to use.
  - title: Flexible Installation
    description: Wiki.js can be installed on virtually any platform and is
      compatible with multiple databases, giving you the freedom to choose the
      setup that works best for you.
  - title: Intuitive Administration
    description: The admin area of Wiki.js allows for easy management of all aspects
      of your wiki, making it simple to customize and control your
      documentation.
  - title: High Performance
    description: Wiki.js is built with performance in mind, running on the blazing
      fast Node.js engine to ensure a smooth and efficient experience.
  - title: Customizable Appearance
    description: You can fully customize the appearance of your wiki, including a
      light and dark mode, to match your branding and preferences.
  - title: Flexible Access Control
    description: You can make your wiki public, completely private, or a mix of
      both, allowing you to control who can access and contribute to your
      documentation.
  - title: Scalable Solution
    description: Whether you're running Wiki.js on a small Raspberry Pi or a
      high-performance VM in the cloud, it intelligently utilizes the available
      resources to ensure optimal performance.
  - title: Easy Installation
    description: With step-by-step install guides available for all platforms, you
      can get started with Wiki.js in just a few minutes.
features:
  - title: Authentication
    description: Wiki.js offers built-in authentication with self-registration and
      password recovery capabilities. It also supports 3rd-party authentication
      services like Google, Facebook, Microsoft, GitHub, Discord, Slack, and
      more. Enterprise authentication options include LDAP, SAML, CAS, Auth0,
      Okta, Azure AD, and more. Two-factor authentication is available for
      supported authentication modules.
  - title: Open Source
    description: Wiki.js is released under the AGPL-v3 license, which means it's not
      just free to use, but anyone can contribute new features and help fix
      bugs.
  - title: Integrations
    description: Wiki.js offers over 50 integrations with external services,
      including Git, AWS, Azure, Google Cloud, Facebook, and Algolia. These
      integrations enhance authentication, logging, rendering, search, and
      storage capabilities.
  - title: Sponsors & Backers
    description: Wiki.js is made possible thanks to generous sponsors and backers
      who support the open source project. Their contributions help fund the
      development and maintenance of Wiki.js.
  - title: Documentation
    description: The official documentation for Wiki.js provides comprehensive
      guides and references for both users and developers. It covers
      installation, configuration, usage, modules, themes, translations, and
      more.
