name: Adminer
description: Adminer is a full-featured database management tool written in PHP.
  It is a single file that can be easily deployed to a server. Adminer supports
  various databases including MySQL, MariaDB, PostgreSQL, SQLite, MS SQL,
  Oracle, Elasticsearch, and MongoDB. It offers a tidier user interface, better
  support for MySQL features, higher performance, and more security compared to
  phpMyAdmin.
instructions: null
changeLog:
  - date: 2022-07-12
    description: first release
links:
  - label: Website
    url: https://www.adminer.org/
  - label: Github
    url: https://github.com/vrana/adminer/
contributors:
  - name: Ponkhy
    url: https://github.com/Ponkhy
  - name: Andrei Canta
    url: https://github.com/deiucanta
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: adminer
    appServiceImage:
      type: string
      title: App Service Image
      default: adminer:4.8.1
tags:
  - Databases
  - Developer Tools
benefits:
  - title: Tidier User Interface
    description: Adminer provides a cleaner and more organized user interface
      compared to phpMyAdmin.
  - title: Better Support for MySQL Features
    description: Adminer offers enhanced support for MySQL features, allowing users
      to fully utilize the capabilities of the database.
  - title: Higher Performance
    description: Adminer is designed to deliver high performance, ensuring efficient
      database management tasks.
  - title: More Security
    description: Adminer prioritizes security and implements measures to protect
      against brute-force attacks and unauthorized access.
features:
  - title: Connect to Database Server
    description: Adminer allows users to connect to a database server using a
      username and password.
  - title: Manage Databases and Tables
    description: Users can create, alter, and drop databases and tables, as well as
      modify table properties such as name, engine, collation, and
      auto_increment.
  - title: Execute SQL Commands
    description: Adminer enables users to execute SQL commands, including creating,
      altering, and dropping indexes, views, stored procedures, and functions.
  - title: Data Manipulation
    description: Users can insert, update, and delete records in tables, as well as
      perform search, aggregate, sort, and limit operations.
  - title: Export and Import Data
    description: Adminer supports exporting table structure, data, views, routines,
      and databases to SQL or CSV files. It also allows importing data from
      files.
  - title: User Management
    description: Adminer provides features for managing users and their rights, as
      well as displaying variables and processes.
