name: Postgres Backup
description: This app allows you to backup your PostgresSQL database to S3, with
  support for periodic backups. It can be run as a Docker container or using
  Docker Compose.
instructions: "In order to test that you configured it properly, remove the
  SCHEDULE variable from the environment, click deploy and check the logs. If
  everything works fine, you can add the SCHEDULE variable back. You can read
  more about the environment variables here:
  https://github.com/schickling/dockerfiles/tree/master/postgres-backup-s3"
changeLog:
  - date: 2022-08-05
    description: first release
links:
  - label: Documentation
    url: https://github.com/schickling/dockerfiles/tree/master/postgres-backup-s3
  - label: Github
    url: https://github.com/schickling/dockerfiles/tree/master/postgres-backup-s3
contributors:
  - name: Andrei Canta
    url: https://github.com/deiucanta
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - host
    - port
    - user
    - password
    - accessKey
    - secretKey
    - bucket
    - prefix
    - region
    - endpoint
    - schedule
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: postgres-backup
    appServiceImage:
      type: string
      title: App Service Image
      default: easypanel/postgres-backup-s3
    host:
      type: string
      title: Postgres Host
    port:
      type: string
      title: Postgres Port
      default: "5432"
    user:
      type: string
      title: Postgres User
      default: postgres
    password:
      type: string
      title: Postgres Password
    accessKey:
      type: string
      title: S3 Access Key
    secretKey:
      type: string
      title: S3 Secret Key
    bucket:
      type: string
      title: S3 Bucket
    prefix:
      type: string
      title: S3 Prefix
      default: backup
    region:
      type: string
      title: S3 Region
      default: us-west-1
    endpoint:
      type: string
      title: S3 Endpoint
    schedule:
      type: string
      title: Schedule
      default: "@daily"
      description: You can use CRON syntax
tags:
  - Databases
  - Backup
benefits:
  - title: Automated backups
    description: You can schedule the backup to run automatically at a specified
      time using the SCHEDULE environment variable.
  - title: Selective backup
    description: You can choose to backup a specific database or all available
      databases by setting the POSTGRES_BACKUP_ALL environment variable.
  - title: Encryption support
    description: You can encrypt the backup file using the ENCRYPTION_PASSWORD
      environment variable.
features:
  - title: Docker support
    description: The app can be run as a Docker container, making it easy to deploy
      and manage.
  - title: Docker Compose support
    description: The app can also be run using Docker Compose, allowing you to
      define and manage the container along with other services.
  - title: Flexible configuration
    description: You can configure various environment variables to customize the
      backup process, such as S3 access credentials, database connection
      details, and backup options.
