name: Tautuilli
description: Tautulli is a web application that allows you to monitor and track
  various statistics of your Plex Media Server. It provides information on what
  has been watched, who watched it, when and where they watched it, and how it
  was watched. The application presents these statistics in a clean and
  user-friendly interface with tables and graphs. Tautulli also offers features
  such as notifications, history logging, media library statistics, and more. It
  is compatible with any system that supports Python.
instructions: null
changeLog:
  - date: 2023-1-26
    description: first release
links:
  - label: Website
    url: https://tautulli.com/
  - label: Github
    url: https://github.com/Tautulli/Tautulli
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: tautuilli
    appServiceImage:
      type: string
      title: App Service Image
      default: lscr.io/linuxserver/tautulli:2.11.1
tags:
  - Media
  - Monitoring
benefits:
  - title: Monitor Plex Media Server Activity
    description: Tautulli allows you to monitor the current activity on your Plex
      Media Server, giving you real-time information on what is being streamed
      and by whom.
  - title: Track Statistics and Analytics
    description: With Tautulli, you can view detailed statistics and analytics about
      your Plex library. This includes information on media playback, user
      activity, streaming trends, and more.
  - title: Receive Notifications
    description: Tautulli provides customizable notifications for stream activity
      and recently added media. You can set up notifications to be triggered by
      specific events on your Plex server.
  - title: Easy to Use and Customize
    description: The web application has a responsive design that can be viewed on
      desktop, tablet, and mobile browsers. It is also easy to configure and
      customize according to your preferences.
features:
  - title: Monitoring
    description: Monitor the current activity on your Plex Media Server, including
      what is being streamed and by whom.
  - title: Statistics
    description: View detailed statistics about your Plex library, including media
      playback, user activity, and streaming trends.
  - title: History
    description: Log and track the watch history for all users on your Plex Media Server.
  - title: Graphs
    description: Visualize streaming trends and statistics using intuitive graphs
      and charts.
  - title: Notifications
    description: Set up notifications or scripts to be triggered by events on your
      Plex server, such as new media additions or user activity.
  - title: Recently Added
    description: Keep track of when new content is added to your Plex library.
  - title: Newsletters
    description: Create and send newsletters featuring recently added media to your
      Plex library.
  - title: Sync
    description: View and manage all synced content from your Plex server.
  - title: Media Info
    description: Access detailed information on all of the media in your Plex library.
  - title: Cross Platform
    description: Tautulli works on any system that supports Python, making it
      compatible with a wide range of devices and operating systems.
  - title: Tautulli Remote
    description: Download the official Tautulli app to view activity and statistics
      on the go.
