name: Rallly
description: Rallly is an open-source scheduling and collaboration tool designed
  to make organizing events and meetings easier. It allows users to create
  meeting polls to find a time that works for everyone. The app is free to use
  and does not require login. It is mobile-friendly and provides notifications
  for participants. Users can also comment on polls. Rallly is open-source and
  self-hostable, giving users full control of their data. The app is ad-free and
  user-funded. It is created by Luke Vella and is available on GitHub.
instructions: null
armSupport: true
changeLog:
  - date: 2023-1-29
    description: first release
links:
  - label: Website
    url: https://rallly.co
  - label: Documentation
    url: https://support.rallly.co/
  - label: Selfhosting Instructions
    url: https://github.com/lukevella/rallly-selfhosted
  - label: Github
    url: https://github.com/lukevella/rallly
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
    - emailSupport
    - emailHost
    - emailPort
    - emailUsername
    - emailPassword
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: rallly
    appServiceImage:
      type: string
      title: App Service Image
      default: lukevella/rallly:2.11.0
    databaseServiceName:
      type: string
      title: Database Service Name
      default: rallly-db
    emailSupport:
      type: string
      title: Support Email
    emailHost:
      type: string
      title: Email Host
    emailPort:
      type: number
      title: Email Port
      default: 587
    emailUsername:
      type: string
      title: Email Username
    emailPassword:
      type: string
      title: Email Password
tags:
  - Calendars
  - Productivity
benefits:
  - title: Streamline your scheduling process
    description: Ditch the back-and-forth emails and use Rallly to easily find a
      time that works for everyone.
  - title: Save time
    description: Rallly helps you save time by automating the scheduling process and
      providing notifications for participants.
features:
  - title: Scheduling, the smart way
    description: Set individual start and end times for each option in your poll.
      Times can be automatically adjusted to each participant's timezone or they
      can be set to ignore timezones completely.
  - title: Mobile friendly
    description: Rallly works great on mobile devices, allowing participants to
      respond to polls wherever they may be.
  - title: Notifications
    description: Keep track of who's responded to your poll and get notified when
      participants vote or comment.
  - title: Comments
    description: Participants can comment on your poll, and the comments will be
      visible to everyone.
  - title: No login required
    description: You don't need to login to create or participate in a poll.
  - title: Open-source
    description: The codebase is fully open-source and available on GitHub.
  - title: Self-hostable
    description: Run Rallly on your own server to take full control of your data.
  - title: Ad-free
    description: Rallly is user-funded and does not display ads.
