name: OneDev
description: OneDev is a self-hosted Git server with Kanban and CI/CD
  capabilities. It provides a complete solution for managing source code,
  tracking issues, and automating build and deployment processes. With OneDev,
  you can easily set up your own Git server and streamline your development
  workflow.
instructions: null
changeLog:
  - date: 2023-02-9
    description: first release
links:
  - label: Website
    url: https://code.onedev.io/
  - label: Documentation
    url: https://docs.onedev.io/
  - label: Github
    url: https://code.onedev.io/onedev/server
contributors:
  - name: spaceb0t
    url: https://github.com/spacec0de
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: onedev
    appServiceImage:
      type: string
      title: App Service Image
      default: 1dev/server:8.1.6
    databaseServiceName:
      type: string
      title: Database Service Name
      default: onedev-db
tags:
  - Code Hosting
  - CI/CD
benefits:
  - title: Self-hosted Git Server
    description: OneDev allows you to host your own Git server, giving you full
      control over your source code and ensuring data privacy and security.
  - title: Kanban Board
    description: OneDev includes a built-in Kanban board for managing your project
      tasks and tracking progress. You can easily create and manage tasks,
      assign them to team members, and track their status.
  - title: CI/CD Automation
    description: OneDev provides a powerful CI/CD engine that allows you to automate
      your build and deployment processes. You can easily configure build
      pipelines, define build specifications, and deploy your applications with
      ease.
features:
  - title: Symbol Search and Navigation
    description: OneDev includes a symbol search and navigation feature that allows
      you to quickly search for symbols in your codebase and navigate to their
      definitions. This makes it easy to explore your code and find specific
      functions or classes.
  - title: Code Search with Regular Expression
    description: OneDev supports code search using regular expressions. You can
      search for specific patterns in your codebase using regular expressions,
      making it easy to find and analyze code snippets.
  - title: Annotate Source/Diff with Static Analysis Result
    description: OneDev allows you to annotate your source code or code diffs with
      static analysis results. This makes it easy to review code and identify
      potential issues or improvements.
  - title: Customizable Issue State and Field
    description: OneDev provides customizable issue states and fields, allowing you
      to tailor the issue tracking process to your specific workflow. You can
      define custom states and fields, and track the progress of your issues
      from creation to resolution.
  - title: Service Desk to Create/Discuss Issues via Email
    description: OneDev includes a service desk feature that allows users to create
      and discuss issues via email. Users can submit tickets via email, and all
      further discussions and updates can be done through email, making it easy
      to collaborate with external stakeholders.
  - title: Powerful and Intuitive Query Language
    description: OneDev provides a powerful query language that allows you to search
      and filter projects, commits, issues, builds, and pull requests. The query
      language supports auto-completions and hints, making it easy to construct
      complex queries.
  - title: Full-fledged CI/CD Engine without Writing Yaml
    description: OneDev includes a full-fledged CI/CD engine that allows you to
      automate your build and deployment processes without writing YAML. You can
      use the GUI to generate CI/CD YAML configurations, making it easy to
      define and manage your build pipelines.
  - title: Flexible Pull Request Review Policy and Reviewer Suggestion
    description: OneDev provides flexible pull request review policies and reviewer
      suggestions. You can specify review policies based on author, branch, and
      changed files, and OneDev can leverage git change history to suggest
      appropriate reviewers for pull requests.
  - title: Lightweight Review without Pull Request
    description: OneDev allows for lightweight code reviews without opening a pull
      request. You can comment on any part of the code or diff, and the comments
      will live through code modifications and file renames. This makes it easy
      to collaborate and provide feedback on code changes.
  - title: Command Palette to Access Features Quickly
    description: OneDev includes a command palette that allows you to quickly access
      features and navigate through the application. You can search for
      projects, files, issues, builds, and settings, and jump to them without
      leaving your keyboard.
  - title: Markdown Editor
    description: OneDev provides a smart editor for writing Markdown. It
      automatically generates image links when uploading images, and tracks your
      cursor position to scroll the preview window. This makes writing Markdown
      documents a pleasant experience.
  - title: SLOC Trend By Language
    description: OneDev calculates the trend of source lines of code (SLOC) by
      language by inspecting the git history of the main branch. This allows you
      to track the growth of your codebase and analyze code changes over time.
  - title: Project Hierarchy
    description: OneDev supports project hierarchy, allowing you to organize your
      projects in a hierarchical structure. Child projects can inherit settings
      from parent projects and selectively override them if needed, reducing the
      overhead of managing multiple projects.
  - title: Fast and Reliable
    description: OneDev is designed for performance and reliability. It has been
      extensively used for more than 5 years and has a proven track record of
      stability. With moderate resource usage, you can enjoy all the features of
      OneDev for medium-sized projects.
