name: Gitea
description: Gitea is a lightweight DevOps platform that brings teams and
  developers high-efficiency but easy operations from planning to production. It
  enables the creation and management of repositories, exploration of commit
  history and code files, review and merging of code commits, collaboration
  management, branch handling, and more. Gitea also supports code review, CI/CD,
  project management, package management, and offers universal compatibility and
  flexible deployment options. It is open-source, secure, and can be tailored to
  meet specific requirements. Gitea integrates with various tools and offers
  support plans for additional benefits.
instructions: null
changeLog:
  - date: 2022-07-12
    description: first release
  - date: 2023-2-24
    description: Update to v1.18.4
links:
  - label: Website
    url: https://gitea.io/en-us/
  - label: Documentation
    url: https://docs.gitea.io/en-us/
  - label: Github
    url: https://github.com/go-gitea/
contributors:
  - name: Ponkhy
    url: https://github.com/Ponkhy
  - name: Andrei Canta
    url: https://github.com/deiucanta
  - name: Supernova3339
    url: https://github.com/supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseType
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: gitea
    appServiceImage:
      type: string
      title: App Service Image
      default: gitea/gitea:1.19.2
    databaseType:
      type: string
      title: Database Type
      oneOf:
        - enum:
            - postgres
          title: Postgres
        - enum:
            - mysql
          title: MySQL
    databaseServiceName:
      type: string
      title: Database Service Name
      default: gitea-db
tags:
  - Code Hosting
  - Developer Tools
benefits:
  - title: High-efficiency DevOps
    description: Gitea streamlines the DevOps process, making it easy for teams and
      developers to plan, develop, and deploy software efficiently.
  - title: Code Review
    description: Gitea provides code review capabilities, allowing reviewers to
      examine code online, submit comments or inquiries, and facilitate enhanced
      code quality.
  - title: CI/CD Integration
    description: Gitea features an integrated CI/CD system, Gitea Actions,
      compatible with GitHub Actions. Users can create workflows using YAML
      format or utilize existing plugins.
  - title: Project Management
    description: Gitea helps manage project requirements, features, and bugs through
      issue tasks, labeling, and kanban project boards. It incorporates
      branches, tags, milestones, assignments, time tracking, deadlines, and
      dependencies.
  - title: Package Management
    description: Gitea supports more than 20 different kinds of public or private
      package management, including popular ones like npm, Maven, and PyPI.
  - title: Open Source
    description: Gitea is an open-source project licensed under the MIT License,
      allowing users to contribute and make the platform better for everyone.
  - title: Universal Compatibility
    description: Gitea is universally compatible with diverse operating systems and
      environments, including Linux, Windows, macOS, Freebsd, and Kubernetes. It
      also supports multiple architectures.
  - title: Flexible Deployment Options
    description: Gitea offers flexible deployment options, supporting both single
      server setups and replication configurations. It seamlessly integrates
      with various databases.
  - title: Secure Code Ownership
    description: Gitea is developed using Golang, a memory-safe language, with a
      focus on security. It supports secure systems, code signing enforcement,
      and WebAuthn-based 2FA login.
  - title: Customizable
    description: Gitea offers various configurations to satisfy diverse user needs.
      It allows enabling or disabling features, customizing site themes, UI
      languages, and more.
  - title: Integration with Favorite Tools
    description: Gitea integrates with popular tools like Slack, Discord, MS Teams
      for chat, and Github Actions, Drone, Woodpecker, ArgoCD, Jenkins for
      CI/CD. It also provides API and webhooks for custom workflows.
  - title: Support Plans
    description: Gitea is available for free under the MIT license with community
      support. Additional support plans are offered for installation/upgrade
      service, professional business support, and customized requirements.
features:
  - title: Code Hosting
    description: Gitea enables the creation and management of repositories,
      exploration of commit history and code files, review and merging of code
      commits, collaboration management, branch handling, and more.
  - title: Code Review
    description: Gitea accommodates both Pull Request and AGit workflows for code
      review. Reviewers can examine code online, submit comments or inquiries,
      and submitters can view and address the feedback.
  - title: CI/CD
    description: Gitea features an integrated CI/CD system, Gitea Actions,
      compatible with GitHub Actions. Users can create workflows using YAML
      format or utilize existing plugins. It also supports third-party CI/CD
      integrations.
  - title: Project Management
    description: Gitea efficiently manages a project's requirements, features, and
      bugs through issue tasks, labeling, and kanban project boards. It
      incorporates branches, tags, milestones, assignments, time tracking,
      deadlines, and dependencies.
  - title: Package Management
    description: Gitea supports more than 20 different kinds of public or private
      package management, including Cargo, Chef, Composer, Conan, Conda,
      Container, Helm, Maven, npm, NuGet, Pub, PyPI, RubyGems, Vagrant, and
      more.
  - title: Open Source
    description: Gitea is an open-source project licensed under the MIT License.
      Users can contribute to make the project better for everyone.
  - title: Accelerate Development & Collaboration
    description: Gitea runs faster with lower resource usage while maintaining
      feature richness. It simplifies development and collaboration processes.
  - title: Run Gitea Anywhere
    description: Gitea offers universal compatibility with diverse operating systems
      and environments. It is compatible with multiple architectures and
      supports various databases. It provides flexible deployment options.
  - title: Powerful built-in CI/CD
    description: Gitea Actions is an internal CI/CD system that offers compatibility
      with GitHub Actions. It has an integrated UI and supports workflow/action
      syntax.
  - title: Securely Own Your Code
    description: Gitea is developed using Golang, a memory-safe language, with a
      focus on security. It is compatible with various secure systems, supports
      branch protection for code signing enforcement, and offers WebAuthn-based
      2FA login.
  - title: Tailor Gitea to Your Requirements
    description: Gitea offers various configurations to satisfy diverse user needs.
      It can be set up as a private or public instance and allows enabling or
      disabling features, customizing site themes, UI languages, and more.
  - title: Integrated with Your Favorite Tools
    description: Gitea integrates with popular tools like Slack, Discord, MS Teams
      for chat, and Github Actions, Drone, Woodpecker, ArgoCD, Jenkins for
      CI/CD. It provides API and webhooks for custom workflows.
  - title: Service Plans
    description: Gitea is available for free under the MIT license. Support plans
      are offered for additional benefits, including installation/upgrade
      service, professional business support, and customized requirements.
