name: CyberChef
description: CyberChef is a simple, intuitive web app for carrying out all
  manner of 'cyber' operations within a web browser. It allows users to perform
  various operations such as encoding, encryption, compression, hashing,
  parsing, and more. The tool is designed to be user-friendly and accessible to
  both technical and non-technical users.
instructions: null
changeLog:
  - date: 2023-2-9
    description: first release
links:
  - label: Documentation
    url: https://github.com/gchq/CyberChef/wiki
  - label: Github
    url: https://github.com/gchq/CyberChef
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: cyberchef
    appServiceImage:
      type: string
      title: App Service Image
      default: mpepping/cyberchef:v10.4.0
tags:
  - Web Hosting
  - Developer Tools
benefits:
  - title: Easy to use
    description: CyberChef provides a simple and intuitive interface that allows
      users to easily perform complex cyber operations without the need for
      complex tools or algorithms.
  - title: Wide range of operations
    description: CyberChef supports a wide range of operations, including encoding,
      encryption, compression, hashing, parsing, and more. Users can combine
      multiple operations to achieve their desired results.
  - title: Automatic encoding detection
    description: CyberChef uses advanced techniques to automatically detect the
      encoding of data, making it easier for users to work with different types
      of data without manual intervention.
  - title: Drag and drop functionality
    description: CyberChef supports drag and drop functionality, allowing users to
      easily load data from files or move operations within the recipe list.
  - title: Save and load recipes
    description: Users can save their recipes for future use and easily share them
      with others. Recipes can be saved locally or copied as a URL, including
      the input and recipe configuration.
features:
  - title: Drag and drop
    description: Operations and files can be dragged and dropped within the app,
      making it easy to rearrange the recipe or load data from files.
  - title: Auto Bake
    description: CyberChef automatically updates the output whenever the input or
      recipe is modified, providing real-time results without manual
      intervention.
  - title: Automated encoding detection
    description: CyberChef uses advanced techniques to automatically detect the
      encoding of data, allowing users to easily decode and work with different
      types of data.
  - title: Breakpoints and step-through execution
    description: Users can set breakpoints on operations in the recipe and step
      through the execution to inspect the data at each stage.
  - title: Save and load recipes
    description: Users can save their recipes for future use and easily load them
      from local storage. Recipes can also be shared by copying the URL.
  - title: Search and highlighting
    description: Users can search for specific operations and highlight text in the
      input or output to see the corresponding data.
  - title: Save to file and load from file
    description: Users can save the output to a file or load a file into the input
      field by dragging and dropping. Large files up to 2GB are supported.
  - title: Client-side processing
    description: All processing in CyberChef is carried out within the user's
      browser, ensuring data privacy and security. The app can also be
      downloaded and run locally.
  - title: Deep linking
    description: CyberChef supports deep linking, allowing users to change the
      initial settings of the app by manipulating the URL hash.
  - title: Browser and Node.js support
    description: CyberChef is built to support Google Chrome 50+, Mozilla Firefox
      38+, and Node.js v16. It can be used both in the browser and as a Node.js
      module.
