name: Fider
description: Fider is a feature-packed solution that allows you to collect
  feedback, suggestions, and bug reports from your customers. It provides a
  platform for your community to share ideas, vote on them, and discuss them.
  With Fider, you can prioritize what your customers need the most and keep
  everyone informed about the progress. It offers one-click sign-in via various
  OAuth2 providers, a private site option for controlling access, custom
  branding with CSS, a public API for integration, multi-language support,
  content organization with tags, Markdown support, and the ability to use your
  own domain. Fider is also open source, allowing you to have total control over
  its implementation. The workflow involves setting up your feedback site,
  inviting people to contribute, and delivering updates to your audience. Fider
  offers a simple pricing plan with no tricks, and you can start with a free
  trial. It also provides documentation on hosting your own instance, API
  reference, and guides on deploying with Docker, Heroku, and Azure, configuring
  SSL/TLS, showing legal pages, and using OAuth and webhooks for integration.
instructions: Fider REQUIRES email in order for installation to work!
changeLog:
  - date: 2022-11-19
    description: first release
links:
  - label: Website
    url: https://fider.io
  - label: Documentation
    url: https://fider.io/docs
  - label: Github
    url: https://github.com/getfider/fider
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
    - emailNoReply
    - emailHost
    - emailPort
    - emailUsername
    - emailPassword
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: fider
    appServiceImage:
      type: string
      title: App Service Image
      default: getfider/fider:stable
    databaseServiceName:
      type: string
      title: Database Service Name
      default: fider-db
    emailNoReply:
      type: string
      title: No Reply Email
    emailHost:
      type: string
      title: Email Host
    emailPort:
      type: number
      title: Email Port
      default: 587
    emailUsername:
      type: string
      title: Email Username
    emailPassword:
      type: string
      title: Email Password
tags:
  - Feedback
  - Productivity
benefits:
  - title: Prioritize what your customers really need
    description: With Fider, you can give your customers a voice and let them tell
      you what they need. Spend less time guessing and more time building the
      right product.
  - title: Trusted by teams all over the world
    description: Fider is trusted by teams all over the world. Join the community
      and be in good company.
features:
  - title: Share ideas, vote and discuss
    description: Fider allows your community to share ideas, vote on them, and
      discuss them. This helps you get valuable suggestions and prioritize what
      your customers need the most.
  - title: Keep everyone informed
    description: Whenever you start, complete, or decline a suggestion, Fider will
      notify everyone subscribed to that topic. This keeps everyone informed
      about the progress.
  - title: One-click sign in
    description: Visitors can easily contribute by signing in via Facebook, Google,
      GitHub, Azure AD, Twitch, Discord, or any other OAuth2 provider. It's just
      one click away.
  - title: Private Site
    description: You have the option to control access to your site by making it
      private. This allows you to limit who can view and contribute to your
      feedback site.
  - title: Your Brand
    description: Customize Fider with your own branding using the custom CSS
      feature. You can style it with your logo, colors, and identity.
  - title: Public API
    description: Fider provides a complete API that allows you to have total control
      and integrate it into your process. Leverage the API to extend the
      functionality of Fider.
  - title: Integrations
    description: Fider can integrate with any system that supports Webhook, such as
      Slack and Discord. This allows you to connect Fider with your existing
      tools and workflows.
  - title: Multi-language
    description: Fider is translated into 10+ languages, including English, Spanish,
      German, French, and Portuguese. This ensures that you can use Fider in
      your preferred language.
  - title: Organize your content
    description: Tag your content in Fider to make it easier to find, group, and
      decide. You can use public or private tags to organize your feedback and
      suggestions.
  - title: Markdown
    description: Style your text in Fider using the popular Markdown markup
      language. This allows you to format your content and make it more
      readable.
  - title: Your own domain
    description: When using Fider's hosted service, you can use your own domain and
      get a free TLS certificate to keep it secure. This gives you full control
      over your feedback site's URL.
  - title: Open Source
    description: Fider is 100% open source, allowing you to have total control over
      its implementation. You can customize and modify it to suit your specific
      needs.
