name: Limesurvey
description: LimeSurvey is an online survey tool that allows users to create and
  design surveys. It offers a simple and quick way to gather insights from
  students, professionals, and enterprises. The tool is free to use and supports
  unlimited answers in over 80 languages. LimeSurvey is trusted by research
  institutes, universities, and other educational establishments for its
  open-source software and easy-to-use templates. It also provides customer
  service support and allows for participant and user management. LimeSurvey is
  praised for its accessibility and has been used by organizations such as the
  Ubuntu Server Team, Austrian Vorarlberg State Government, and Ars Electronica.
  The tool also offers corporate solutions with custom features and support.
  Pricing plans are available for different budgets and purposes. LimeSurvey is
  developed by LimeSurvey GmbH, a company that has been in operation since 2006.
instructions: null
changeLog:
  - date: 2023-01-24
    description: first release
links:
  - label: Website
    url: https://limesurvey.org/
  - label: Documentation
    url: https://manual.limesurvey.org
  - label: Github
    url: https://github.com/LimeSurvey/LimeSurvey
contributors:
  - name: Supernova3339
    url: https://github.com/supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
    - limesurveyUsername
    - limesurveyPassword
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: limesurvey
    appServiceImage:
      type: string
      title: App Service Image
      default: tiredofit/limesurvey:1.5.10
    databaseServiceName:
      type: string
      title: Database Service Name
      default: limesurvey-db
    limesurveyUsername:
      type: string
      title: Username
    limesurveyPassword:
      type: string
      title: Password
tags:
  - Productivity
  - CMS
benefits:
  - title: Simple and Quick
    description: LimeSurvey offers a simple and quick way to create and design
      surveys, making it easy for users to gather insights.
  - title: Unlimited Answers
    description: Users can collect unlimited answers in their surveys, allowing for
      comprehensive data collection.
  - title: Multilingual Support
    description: LimeSurvey supports over 80 languages, making it accessible to a
      global audience.
  - title: Trusted by Educational Establishments
    description: LimeSurvey is trusted by research institutes, universities, and
      other educational establishments for its open-source software and
      user-friendly templates.
  - title: Customer Service Support
    description: LimeSurvey provides customer service support to assist users with
      their survey needs.
  - title: Participant and User Management
    description: Users can easily manage participants and user rights within LimeSurvey.
  - title: Accessibility
    description: LimeSurvey is praised for its accessibility and has been the
      preferred choice for organizations such as the Ubuntu Server Team,
      Austrian Vorarlberg State Government, and Ars Electronica.
  - title: Corporate Solutions
    description: LimeSurvey offers custom features and support for corporate users,
      catering to their specific needs.
  - title: Flexible Pricing Plans
    description: LimeSurvey offers pricing plans for different budgets and purposes,
      ensuring that users can find a plan that suits their needs.
features:
  - title: Design and Create Surveys
    description: LimeSurvey allows users to design and create surveys with ease,
      offering a range of customization options.
  - title: Alternative to Google Forms and Doodle
    description: LimeSurvey provides an alternative to Google Forms and Doodle,
      offering more advanced features and capabilities.
  - title: Advanced Survey Features
    description: LimeSurvey supports complex validation rules, conditional logic,
      and quota management, allowing users to create sophisticated surveys.
  - title: Open-Source Software
    description: LimeSurvey is built on open-source software, providing users with
      the freedom to customize and modify the tool to suit their needs.
  - title: Easy-to-Use Templates
    description: LimeSurvey offers easy-to-use templates, making it simple for users
      to get started with their surveys.
  - title: Customizable Survey Goals
    description: Users can quickly achieve their survey goals with LimeSurvey,
      thanks to its range of tools and features.
  - title: Custom Number of Responses
    description: LimeSurvey offers the flexibility to set a custom number of
      responses per year, allowing users to control their survey limits.
  - title: Custom Upload Storage
    description: Users can customize their upload storage capacity within
      LimeSurvey, ensuring they have enough space for their survey data.
  - title: Corporate Support
    description: LimeSurvey provides dedicated corporate support, catering to the
      specific needs of corporate users.
  - title: Custom Number of Alias Domains
    description: Users can set a custom number of alias domains within LimeSurvey,
      allowing for branding and customization.
  - title: Dedicated Server
    description: LimeSurvey offers the option of a dedicated server for users who
      require additional resources and control.
