name: Nango
description: Nango is an open-source product integration platform that allows
  developers to build integrations quickly and maintain full control. It
  provides pre-built (O)Auth, API configuration, and templates for over 100
  APIs. With Nango, developers can authorize integrations, sync data with
  external APIs, and unify integration code using a single API and unified
  models. The platform offers managed API authentication, bi-directional sync,
  real-time updates through webhooks, and an admin console to monitor activity
  and traffic. Nango supports any API and any use case, with templates for 100+
  APIs out-of-the-box and the ability to add custom APIs. It is language
  agnostic and works with every programming language and framework. Nango is
  100% open source, allowing developers to leverage the community's shared
  knowledge and contributions. The platform is loved by developers and CTOs for
  its ease of use, time-saving capabilities, and seamless OAuth implementation.
  Nango offers both self-hosted and cloud options for deployment.
instructions: Check the environment tab for your API key. Follow the
  instructions in the FILE mount.
changeLog:
  - date: 2023-3-13
    description: first release
links:
  - label: Website
    url: https://nango.dev
  - label: Documentation
    url: https://docs.nango.dev
  - label: Github
    url: https://github.com/NangoHQ/nango
contributors:
  - name: Supernova3339
    url: https://github.com/Supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
    - webUsername
    - webPassword
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: nango
    appServiceImage:
      type: string
      title: App Service Image
      default: nango.docker.scarf.sh/nangohq/nango-server:0.10.3
    databaseServiceName:
      type: string
      title: Database Service Name
      default: nango-db
    webUsername:
      type: string
      title: Username
    webPassword:
      type: string
      title: Password
tags:
  - API
  - Security
benefits:
  - title: Build integrations fast
    description: Nango provides pre-built (O)Auth, API configuration, and templates
      for over 100 APIs, allowing developers to build integrations quickly.
  - title: Maintain full control
    description: With Nango, developers have full control over their integrations.
      They can customize pre-built integrations, build their own on top of
      Nango's infrastructure, and manage user credentials securely.
  - title: Simplify integration code
    description: Nango offers unified models and a single API, simplifying
      integration code. Developers don't need to deal with each external API's
      schema and quirks anymore.
  - title: Support for any API and use case
    description: Nango supports any API and any use case. It provides templates for
      100+ APIs out-of-the-box and allows developers to add custom APIs easily.
  - title: Language agnostic
    description: Nango works with every programming language and framework.
      Developers can leverage Nango's typed SDK in multiple languages or call
      the unified API directly.
  - title: Open source community
    description: Nango is 100% open source, allowing developers to leverage the
      community's shared knowledge and contributions. The platform is actively
      maintained and updated by a team and community of contributors.
features:
  - title: Managed API auth
    description: Nango provides a drop-in UI to let users authorize integrations. It
      handles various authentication types (OAuth, API Key) and securely manages
      user credentials.
  - title: Bi-directional sync
    description: Nango continuously synchronizes data with external APIs in the
      background, ensuring data is always up to date.
  - title: Real-time updates
    description: Nango offers webhooks to get real-time updates on data changes from
      external APIs.
  - title: Unified API & models
    description: Nango provides a single API with documented and structured schemas,
      simplifying integration code and eliminating the need to deal with each
      external API's schema and quirks.
  - title: Custom objects
    description: Users can define custom objects and access the raw data through
      Nango, giving them flexibility and control over their integrations.
  - title: Typed SDKs
    description: Nango's typed SDKs offer auto-completion, strong types, and concise
      syntax, making integration development easier and more efficient.
  - title: Admin console
    description: Nango provides an admin console where users can inspect their
      customers' activity and traffic related to integrations.
  - title: Monitoring
    description: Nango ensures reliable external integrations with unified error
      reporting, allowing developers to identify and resolve issues quickly.
