name: Filebrowser
description: File Browser is a file managing interface that allows you to
  upload, delete, preview, rename, and edit files within a specified directory.
  It also supports multiple users with their own directories. It can be used as
  a standalone app.
instructions: 'Default credentials: User:"admin" Password:"admin"'
changeLog:
  - date: 2022-08-09
    description: first release
  - date: 2023-2-24
    description: Update to v2.23.0
links:
  - label: Website
    url: https://filebrowser.org/
  - label: Github
    url: https://github.com/filebrowser/filebrowser
contributors:
  - name: Bedeoan Raul
    url: https://github.com/bedeoan
  - name: Andrei Canta
    url: https://github.com/deiucanta
  - name: Supernova3339
    url: https://github.com/supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
  properties:
    projectName:
      type: string
      title: Project Name

    appServiceName:
      type: string
      title: App Service Name
      default: filebrowser
    appServiceImage:
      type: string
      title: App Service Image
      default: filebrowser/filebrowser:v2-s6
tags:
  - File Management
  - CMS
benefits:
  - title: Easy File Management
    description: File Browser provides a user-friendly interface for managing files,
      making it easy to perform common file operations.
  - title: Customization Options
    description: You can customize your File Browser installation by changing its
      name, adding a custom style sheet, and using your own logo.
  - title: Command Runner
    description: The Command Runner feature allows you to execute shell commands
      before or after certain events, providing flexibility and automation.
features:
  - title: Authentication Method
    description: You can change the way users authenticate with the File Browser server.
  - title: Command Line Interface
    description: File Browser provides a command line interface for advanced users
      who prefer working with the terminal.
  - title: Contributing
    description: If you're interested in contributing to the project, there are
      guidelines available to help you get started.
