name: Rocket.Chat
description: Rocket.Chat is a customizable open-source communications platform
  for organizations with high data protection standards. It enables real-time
  conversations between colleagues, other companies, or customers across web,
  desktop, or mobile devices. Rocket.Chat integrates with multiple conversation
  channels and offers a mobile app for easy access. It can be deployed on your
  server or used as a SaaS solution. Rocket.Chat 6.0 is the latest version,
  offering enhanced security and scalability.
instructions: null
changeLog:
  - date: 2022-08-10
    description: first release
  - date: 2023-3-20
    description: Update to v5.4.5
links:
  - label: Website
    url: https://rocket.chat/
  - label: Documentation
    url: https://docs.rocket.chat/
  - label: Github
    url: https://github.com/RocketChat/Rocket.Chat
contributors:
  - name: Bedeoan Raul
    url: https://github.com/bedeoan
  - name: Andrei Canta
    url: https://github.com/deiucanta
  - name: Supernova3339
    url: https://github.com/supernova3339
schema:
  type: object
  required:
    - projectName
    - appServiceName
    - appServiceImage
    - databaseServiceName
  properties:
    projectName:
      type: string
      title: Project Name
    appServiceName:
      type: string
      title: App Service Name
      default: rocketchat
    appServiceImage:
      type: string
      title: App Service Image
      default: rocketchat/rocket.chat:5.4.5
    databaseServiceName:
      type: string
      title: Database Service Name
      default: rocketchat-db
tags:
  - Communication
  - Security
benefits:
  - title: Secure and Compliant
    description: Rocket.Chat ensures data privacy and security, supporting
      compliance with GDPR, HIPAA, and other regulations.
  - title: Customizable and Flexible
    description: Rocket.Chat can be customized and integrated with your ecosystem
      using open APIs. It offers a wide range of customization and
      white-labeling options.
  - title: Team Collaboration
    description: Bring together messages, projects, and tasks into one place to
      improve team productivity.
  - title: Omnichannel Customer Service
    description: Engage in seamless interactions with customers across various
      channels, ensuring great customer experiences.
  - title: Chat Engine
    description: Create custom messaging experiences within your app or website by
      integrating Rocket.Chat components.
  - title: Marketplace
    description: Extend and customize your workspace with custom apps, plugins, and
      webhooks from the Rocket.Chat Marketplace.
features:
  - title: Team Collaboration
    description: Bring together messages, projects, and tasks into one place to
      improve team productivity.
  - title: Omnichannel Customer Service
    description: Engage in seamless interactions with customers across various
      channels, ensuring great customer experiences.
  - title: Chat Engine
    description: Create custom messaging experiences within your app or website by
      integrating Rocket.Chat components.
  - title: Marketplace
    description: Extend and customize your workspace with custom apps, plugins, and
      webhooks from the Rocket.Chat Marketplace.
  - title: 100% in Control
    description: Choose from self-hosted, air-gapped, or secure cloud deployment
      options that meet your security and compliance needs.
  - title: 100% Privacy
    description: Rocket.Chat is E2E encrypted, ISO 27001 certified, and supports
      compliance with GDPR, HIPAA, and other regulations.
  - title: 100% Customizable
    description: Integrate with your ecosystem using open APIs and enjoy a wide
      range of customization and white-labeling options.
